### ISSUE TITLE
Investigate showing tutorial notebooks in documentations.

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#100]
Ask Stef as well.

**Comment by elboyran** [comment]
Blocking issue #94

**Comment by cwmeijer** [comment]
Elena and Chris don't know about this. Could any of you please provide details what this is about and how to complete this issue?
@egpbos @geek-yang @loostrum

**Comment by loostrum** [comment]
It's about showing notebooks in the rendered docs, possibly interactively. I vaguely remembered that Stef tried something like this, so we should talk to him.

**Comment by loostrum** [comment]
See e.g. example at the top of this page: https://thebe.readthedocs.io/en/latest/

**Comment by loostrum** [comment]
I talked to Stef about it this morning. He made documentation using jupyter notebooks, see [here](https://nanomesh.readthedocs.io/en/latest/examples/How%20to%20generate%20a%20triangle%20mesh%20from%20a%202D%20image.html)
It was done using `nbsphinx` and `nblink` to link the files (the latter is optional).
Note that these notebooks are not interactive.

Do we want to try this out? And/or entangled?
