### ISSUE TITLE
Documentation for top level functionality:

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#101]
inventory and fill the gaps.
Might be solved by the linting doc. 
See PR #74.

**Comment by egpbos** [comment]
@cwmeijer and I have been using the failing docstring linting messages to fill the gaps.

**Comment by egpbos** [comment]
Everything is now documented. Whether it is documented well is a different matter, see #107. I think this issue can be closed now, if anyone disagrees, please feel free to reopen.
