### ISSUE TITLE
Find out if  we can use the JOSS template for our documentation/README

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#102]

**Comment by elboyran** [comment]
Blocking issue #94

**Comment by elboyran** [comment]
The JOSS (Journal of Open Source Software), does not have a README template as such, but the short paper is a up to 1000 words markdown with a structure similar to that of a README. The [submission instructions](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) show the structure of the paper and an [example](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) is given.  

It seems like a good idea to already address the **relevant** (my proposal) elements in our README:

-    A list of the authors of the software and their affiliations, using the correct format (see the example below).
- **A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.**
- **A Statement of Need section that clearly illustrates the research purpose of the software.**
-   A list of key references, including to other software addressing related needs. Note that the references should include full names of venues, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline.
- **_Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it._**
-    Acknowledgement of any financial support.

**Comment by egpbos** [comment]
I converted all items you mentioned into separate issues.
