### ISSUE TITLE
design logo for dianna

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#104]
for use in repo's readme, presentations and anywhere else

**Comment by elboyran** [comment]
Something like [this](https://en-academic.com/dic.nsf/enwiki/3546653) ;-)?
Or more like [this](https://en-academic.com/dic.nsf/enwiki/3546653)?

**Comment by elboyran** [comment]
Just having some fun with [https://socialbook.io/cartoonize](https://socialbook.io/cartoonize). Do they look like Dianna, the Roman hunt goddess, searching the truth/insight and a heatmap at the same time? ;-)

![Seignac,_Diane_chassant_(5613442047)_1641910793275 jpg-socialbook-preview1](https://user-images.githubusercontent.com/3244249/148960661-b4cf70a3-9500-43af-a390-bda4ef632bc6.png)
![Seignac,_Diane_chassant_(5613442047)_1641910793275 jpg-socialbook-preview2](https://user-images.githubusercontent.com/3244249/148960668-57ecb526-8382-4611-a661-7b56b2f0ff3a.png)
.

**Comment by elboyran** [comment]
![Diana_greek_text_alighed](https://user-images.githubusercontent.com/3244249/148973780-57d82177-6e37-4146-8878-893220af91fd.png)

**Comment by egpbos** [comment]
Haha, very nice, that's a cool avatar. I think for a logo we need it to be more stylized, i.e. only using a very small icon-like probably monochromatic representation of this. Maybe the arrow or the bow or the quiver?

**Comment by egpbos** [comment]
For instance, something like [this](https://www.dreamstime.com/quiver-icon-vector-isolated-white-background-your-web-mobile-app-design-quiver-logo-concept-quiver-icon-vector-sign-image134155080) or [this](https://www.dreamstime.com/quiver-icon-trendy-design-style-isolated-white-background-vector-simple-modern-flat-symbol-web-site-mobile-logo-app-image135749552). We could put the quiver in front of DIANNA (in a nice classical looking font) and the bow behind it, though maybe that's already too crowded again and just a quiver would be neater.

**Comment by cwmeijer** [comment]
I like these last designs. Very nice. They are a bit wild still. Elements are the bow, the net, and the red and blue heatmap. How about one without the bow (which I also like, but something seems to be too much here)?
Would you mind sharing an editable file so we can fiddle around with it?

**Comment by egpbos** [comment]
Ooh, yeah very nice. I also agree with @cwmeijer. Maybe just a D with an arrow, which already looks like a bow as well and is a bit quieter?

**Comment by elboyran** [comment]
> Ooh, yeah very nice. I also agree with @cwmeijer. Maybe just a D with an arrow, which already looks like a bow as well and is a bit quieter?

I wanted to do exactly that, but didn't see a quick way, I simply used Word icons (and shapes)- they had a bow with arrow, but not just an arrow ;-). I did that for 15 mins only as an idea.

**Comment by elboyran** [comment]
> I like these last designs. Very nice. They are a bit wild still. Elements are the bow, the net, and the red and blue heatmap. How about one without the bow (which I also like, but something seems to be too much here)? Would you mind sharing an editable file so we can fiddle around with it?

Sure, just a Word file (in which I didn't even manage to remove a blue ellipse after I made it ;-) ), I'm afraid..
[DIANNA Logo Designs.odt](https://github.com/dianna-ai/dianna/files/7887702/DIANNA.Logo.Designs.odt)
.

**Comment by cwmeijer** [comment]
![image](https://user-images.githubusercontent.com/6087314/149975724-6a2de604-886d-4249-bb8b-93f7d54de8b1.png)
![image](https://user-images.githubusercontent.com/6087314/149975856-07f457f9-ab1b-4d1a-9079-12ffbb604848.png)
I'll try some more later.

**Comment by cwmeijer** [comment]
Or with some public domain quiver :-)
![image](https://user-images.githubusercontent.com/6087314/150114641-fe0c4cdb-fdbe-44f6-8bdc-09a024bf8b89.png)
[DIANNA.Logo.Designs.odt](https://github.com/dianna-ai/dianna/files/7896347/DIANNA.Logo.Designs.odt)

**Comment by egpbos** [comment]
![Schermafbeelding 2022-01-19 om 12 11 24](https://user-images.githubusercontent.com/6146598/150118883-82747145-ba53-4b80-a2f2-8c0e46fba399.png)

**Comment by elboyran** [comment]
> ![Schermafbeelding 2022-01-19 om 12 11 24](https://user-images.githubusercontent.com/6146598/150118883-82747145-ba53-4b80-a2f2-8c0e46fba399.png)

I had such a version, but didn't like it.

**Comment by elboyran** [comment]
Somehting like this? The arrow is not very pretty, but don't know how to add nodes to the Word shape...

<img width="548" alt="Logo_ER4" src="https://user-images.githubusercontent.com/3244249/150372209-2e369a69-d2b3-43d0-b0c7-b1fe5bd16348.png"> 

[DIANNA Logo Designs.odt](https://github.com/dianna-ai/dianna/files/7906561/DIANNA.Logo.Designs.odt)

**Comment by cwmeijer** [comment]
maybe we can connect the horizontal lines of the 'a's and 'd' to form one longer arrow striking through the whole word

**Comment by elboyran** [comment]
> maybe we can connect the horizontal lines of the 'a's and 'd' to form one longer arrow striking through the whole word

What would be the idea? My idea was to have a bow (D plus arrow) a Neural Network and heatmap-like blobs.

**Comment by egpbos** [comment]
Arrow all the way through:
![Schermafbeelding 2022-01-25 om 10 15 19](https://user-images.githubusercontent.com/6146598/150947494-c23ee7bf-06a6-4a16-9a62-affed84f2d3e.png)

Arrow lined up with A-bars:
![Schermafbeelding 2022-01-25 om 10 16 22](https://user-images.githubusercontent.com/6146598/150947686-3116e53a-c5b6-4d10-9645-5d553d2c4b27.png)

I think the latter is better for symmetry, but it would be even nicer if we had a font that had the A-bars in the middle of the D's height so the arrow was in the middle...

**Comment by egpbos** [comment]
![Schermafbeelding 2022-01-25 om 10 23 39](https://user-images.githubusercontent.com/6146598/150948926-176c1690-6234-4262-957a-279fd8fb555a.png)
We can make the D bigger to get that symmetry :D

**Comment by elboyran** [comment]
Or this? I was not aiming for symmetry, but for pointing at the NN ;-)
<img width="391" alt="Logo_ER7" src="https://user-images.githubusercontent.com/3244249/150966039-3e07d4e8-a012-4815-82cc-54db79bcd20a.png">

[DIANNA Logo Designs.odt](https://github.com/dianna-ai/dianna/files/7933030/DIANNA.Logo.Designs.odt)

**Comment by egpbos** [comment]
Well, then you should rotate the D and arrow to actually point to the NN thingy :D

**Comment by elboyran** [comment]
What about just using NLeSc-like colours?:
![Logo_ER8](https://user-images.githubusercontent.com/3244249/151066333-76ec2110-3bb0-4d1f-8c3c-de5d79a19ff3.png)

[DIANNA Logo Designs.odt](https://github.com/dianna-ai/dianna/files/7937486/DIANNA.Logo.Designs.odt)

**Comment by egpbos** [comment]
Ooh, I like these ones. I think I liked the other network icon better, this one is a bit too detailed, but other than that: ship it! ;)

**Comment by cwmeijer** [comment]
I like the new ones. However, the new network icon reminds me a bit too much like the atomium in Brussels in my opinion. The other one looked more generic somehow. I prefer the old one as well.
I like the italic version of these last two ones but the fact that the arrow is not italic bugs me a bit. Can the vertical lines in the arrow be parallel to the verical lines in of the italic font? I'm aiming at the vertical line at the tip of the arrow, and one imaginary line connecting the 2 tail tips of the arrow.

Oh and unrelated to that, I made this based on one of Patrick's last remixes of the logo:
![logo](https://user-images.githubusercontent.com/6087314/151385589-d9232512-17c1-4862-8307-226191039a92.png)

**Comment by cwmeijer** [comment]
I like the purple/blue ones. However, the new network icon reminds me a bit too much like the atomium in Brussels in my opinion. The other one looked more generic somehow. I prefer the old one as well.
I like the italic version of these last two ones but the fact that the arrow is not italic bugs me a bit. Can the vertical lines in the arrow be parallel to the verical lines in of the italic font? I'm aiming at the vertical line at the tip of the arrow, and one imaginary line connecting the 2 tail tips of the arrow.

**Comment by elboyran** [comment]
Sorry I don't agree that the first is better, it was an icon for "network", this one is for "neural network". Looks like the Atomium to you only because it's rotated (to fit between the 2 Ns), but to me the other one looks much more like the [Atomuim](https://en.m.wikipedia.org/wiki/File:Atomium_Belgium_1.jpg) ;-) It takes big efford to import it and scale the new icon every time in Word as for some bizzare reason after a while and definitely when saving, it degrdes quality, so will see if I can edit the arrow, so far I didn't manage to get access to its contour nodes...

**Comment by elboyran** [comment]
@cwmeijer , something in these lines (Word arrow shape, whose nodes and segments' curvature can be edited)? Alighted with what- the "I" or the left stroke of the "A"? How the lines of the arrow's head should be aligned? [The network is in bad quality will be fixed last.]
![Logo_ER10](https://user-images.githubusercontent.com/3244249/151783146-6a215cf4-82f6-4a56-8023-0edce3bc50c5.png)
[DIANNA Logo Designs.docx](https://github.com/dianna-ai/dianna/files/7970234/DIANNA.Logo.Designs.docx)

**Comment by cwmeijer** [comment]
Yeah looks great!
How about putting the network on its side then? Inputs left, outputs right. This would put the hidden nodes on a vertical line. We could then, if we'd like, skew the network a bit as to have the nodes of every layer follow the same angle as the italic font.

**Comment by elboyran** [comment]
The logos for DIANNA: software and datasets are at the [DIANNA Sharepoint](https://nlesc.sharepoint.com/:f:/s/DIANNA/EjLIGLupByZJgs2w5nMSYiQByuRHX-AlSCaScZcCA-2u9w?e=5sYhSB).
