### ISSUE TITLE
Put models in central location for models

### ISSUE THREAD

**Issue by loostrum** [dianna-ai/dianna#108]
Currently we have some of our onnx models in the tests/test_data folder.
That is fine for tests, but a bit awkward when loading a model in a tutorial notebook.
Should we have a central location for our models? A separate repo? Zenodo?

Edit:
| Model |  Zenodo link |
| --- | --- |
| leafsnap |  
| geometric |
| binary mnist |
| movie reviews |

**Comment by cwmeijer** [comment]
Standup: Zenodo.

**Comment by egpbos** [comment]
Isn't that inconvenient? Why not just a models folder in the repo? If we're going through with this, I would propose that we also make a little function that downloads them automatically when needed. For instance, `dianna.models` could contain paths to the models, or just functions that load the models automatically, and when they do and the models aren't present yet, it will download them.

**Comment by loostrum** [comment]
Yes the idea would be to add some automatic download functions.

A reason to not put them in the repo is that anyone that installs dianna would also download the models while they don't need them unless they want to do the tutorials. The models are only about 8MB in total. Not that much, but times hopefully a lot of users it adds up.

**Comment by loostrum** [comment]
The models are now on zenodo
