### ISSUE TITLE
Suggestions to improve the documentation

### ISSUE THREAD

**Issue by fdiblen** [dianna-ai/dianna#116]
## General comments

The README intro reads too much like a paper intro. It should be shorter and more to the point, then extended with the current information. It is not clear from the README explanation who is target user of the package, and what software stack it supports. In the first paragraph, it could have this information. For instance, “DIANNA provides insight tools for Deep Learning frameworks in order to increase the explainability of these models. It supports PyTorch and Tensorflow in addition to blah.” 

Furthermore, you need to be more explicit about “non-specialist researcher user”. What experience does the user need to use DIANNA? For example experience with PyTorch/Tensorflow, ONNX and familiarity with Explainable AI? You should define the target user profile.

Anything that is “new” to the user could be reinforced. This could also help promote the DIANNA docs as the first contact about some of these topics, e.g. “Have you heard about XAI? See how to make your Deep Learning model explainable here.” 

## Specific Suggestions 

- [x] Remove or fix “How to use dianna” section 

- [x]  Move the badges to top of the README.md

- [ ] #144
- List requirements (tools that the user needs to install) 
- Add links for all the external tools 

- [ ]  Tell what Python versions, Operating systems etc. are supported
- Give details about development environment and test environment
- Make sure you have up to date developer documentation (see README.dev.md)

- [x]  Fix the CII badge by creating one (see https://bestpractices.coreinfrastructure.org/en)

- [x]  There is no text in “Documentation” section of README.md

- Add a documentation page listing and explaining the different methods 
- Add a documentation page listing and explaining the different visualizations 
- Docstrings in the code could have a brief explanation of the method. 
- Update and maintain the CHANGELOG.md or remove it

- [x]  Add a ROADMAP.md (can be an open project on GitHub with linked issues) to tell users what they should expect from upcoming  releases. Having an estimated timeline would also help. 

## Tutorials

- Add tutorials (newcomer friendly guided tour) and how to guides (focused solutions to specific problems) to the site (see [1]) 
- Add an overview of Jupyter notebooks, explaining what user will be doing in each Jupyter notebook
- Reusing Jupyter notebooks is a good idea, but they need comments and motivation 
- What is the machine learning software stack? How do I install it? 
- How do I interpret the result?

One tip is to not differentiate the tutorials and how to guides by name (i.e., don’t create different sections for them), since the nomenclature of [1] is not widely known, especially by users. Instead, just give good titles, e.g., “Introduction to DIANNA” can be a tutorial, with an overview of everything; “Explainable AI using Tensorflow and DIANNA” can be a tutorial, more focused. “How to choose which DIANNA method to use” can go more to the point. 

## References

[1] https://diataxis.fr

---
Please let us know if something is not clear or if you need more input.
Faruk on behalf of GT

**Comment by elboyran** [comment]
Thanks, Faruk and GT! It could have been better if you had look at the documentation today as we were not ready to show something earlier (so some of the points are already addressed or in the process of being addressed), but maybe I wasn't clear in my request ;-). 
Your feedback is very useful! Maybe we will ask for another "review" later ;-)

**Comment by elboyran** [comment]
BTW we support and advertise ONNX it should "rule them all" other formats ;-)

**Comment by egpbos** [comment]
All unaddressed suggestions have been given separate issues. Thanks again for the feedback!
