### ISSUE TITLE
TypeError: explain_image() got an unexpected keyword argument 'p_keep'

### ISSUE THREAD

**Issue by geek-yang** [dianna-ai/dianna#119]
This error is due to the existence of a local variable in `RISE.explain_image()` which name is also `p_keep`. When using the top level API of DIANNA, the keyword arguments are passed by:
```
explain_image_kwargs = utils.get_kwargs_applicable_to_function(explainer.explain_image, kwargs)
return explainer.explain_image(model_or_function, input_data, labels, **explain_image_kwargs)
```
Since `utils.get_kwargs_applicable_to_function()` checks arguments by comparing `function.__code__.co_varnames`, all local variables with the same name as given keyword arguments will be passed to `explainer.explain_image()`.

**Comment by geek-yang** [comment]
An easy way to fix this, is to make the local variable `p_keep` as `self.p_keep`.

**Comment by loostrum** [comment]
I'd prefer to try to fix this in `get_kwargs_applicable_to_function` if possible, as apparently it's not doing exactly what we'd expect if it includes local variables. `inspect.getfullargspec(func).args` might do what we want: it includes (keyword) arguments, but not local variables.
