### ISSUE TITLE
macOS setup-python python binary not used

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#122]
It seems like in macOS builds, we are somehow using the setup-python action wrong. The version that is installed is not picked up in the version check right thereafter and also not in the later commands where we install dependencies and DIANNA itself. In effect, we have been using only the macOS system provided Python 3.9 for a while now.

Right now, this is causing an issue, because for some weird reason it complains about bdist_wheels, for instance in [this build](https://github.com/dianna-ai/dianna/runs/4870226137?check_suite_focus=true). Note that I didn't change anything in the build there, so it seems to really be caused by external factors.

**Comment by loostrum** [comment]
That complaint would happen if the system python doesn't have wheel installed, which might be the case I guess.

I see e.g. in (this)[https://github.com/dianna-ai/dianna/runs/4869969506?check_suite_focus=true] action by the way that while the python info shows the wrong version, the unit tests are using the right version. 

Could it be that only the `python` executable is the newly installed version, while `python3` still points to the system version? Both the wheel build and python info use `python3` explicitly.

**Comment by egpbos** [comment]
I'll try!

**Comment by egpbos** [comment]
Oh, damn, I think it *is* caused by a minor edit of mine, haha. I added `shell: bash -l {0}` to the run things, which apparently causes problems: https://github.com/actions/setup-python/issues/179

**Comment by loostrum** [comment]
Ah nice catch!

**Comment by egpbos** [comment]
Fixed by removing the `-l` option to bash.
