### ISSUE TITLE
Remove Tensorflow dependency in dianna

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#123]
Recently, tensorflow was added as an dependency for dianna. We hoped to keep tensorflow and torch and such from our dependency list. Also, tf doesn't seem to be imported anywhere, except for our example notebooks.
Can we remove the dependency again?

**Comment by loostrum** [comment]
It might be needed for onnx-tf, but then it should be a dependency of onnx-tf and not of dianna. It was added in e9ce190aee8b0a2edfc55be448438ed38a0cf96d which is about shap, but shap doesn't use it indeed. I think it can be removed, unless it breaks onnx-tf

**Comment by egpbos** [comment]
Unfortunately, onnx-tf does need tensorflow, it seems, but it doesn't have it as a dependency, as explained here: https://github.com/onnx/onnx-tensorflow#production-installation

So if we want to keep using onnx-tf, we do need to install it.

It could be an optional dependency that people should install themselves, just as onnx-tf does, but I think it's a bit sloppy.

**Comment by loostrum** [comment]
Seems like we need to keep the dependency so I'll close this issue. Feel free to reopen if someone disagrees.
