### ISSUE TITLE
Turn off Sonarcloud spam

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#129]
Can we please turn off the Sonarcloud messages in PR threads?

Here's the howto: https://jira.sonarsource.com/browse/SCCOMM-19

I think @loostrum is the Sonarcloud admin, this should be the direct link to the correct admin page: https://sonarcloud.io/project/settings?category=pull_request&id=dianna-ai_dianna

**Comment by loostrum** [comment]
Done, thanks for the howto!
I've made the others that have their Github connected to sonarcloud admin as well.

@elboyran and @cwmeijer: you're not on sonarcloud yet it seems. If you want to be an admin of the dianna project on sonarcloud you can log in to sonarcloud.io with your Github and then let me know so I can make you admin.
