### ISSUE TITLE
Make `label` a required argument

### ISSUE THREAD

**Issue by loostrum** [dianna-ai/dianna#131]
Now the `label` argument is a keyword argument with a default of either 0 or 1, depending on the method.
Doesn't it make more sense to always ask the user which class they want an explanation for instead of assuming one?

**Comment by egpbos** [comment]
Sounds reasonable to me.

I'm thinking that refactoring the classes into more specific ones that also mention what task they do, so e.g. `LimeImageClassifier` ([name][modality][task]) as mentioned in https://github.com/dianna-ai/dianna/issues/91#issuecomment-1008977867, would also support this way of working. It should immediately be clear from the name `Classifier` that a class to explain must be provided. Similarly, for possible other tasks in the future, other arguments may be clear (e.g. a distance metric when you want to explain distance).

**Comment by cwmeijer** [comment]
See PR #426.
