### ISSUE TITLE
readme/JOSS: add/check statement of need section

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#138]
JOSS needs: "A Statement of Need section that clearly illustrates the research purpose of the software."

@elboyran was already working on a "Why DIANNA?" section in #113 that seems to fit this well, so maybe it is already done, but let's check against the JOSS example: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography.

**Comment by elboyran** [comment]
Will address also #144 .

**Comment by elboyran** [comment]
Decided to move the text for other tools + JOSS statement of need in a separate file. Add 1-2 sentences in the readme- the essence and point to that file.

**Comment by elboyran** [comment]
Solved by #177
