### ISSUE TITLE
readme/JOSS: add references section

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#139]
Since we want to be cited, we should obviously also cite others :) JOSS mandates this for their submissions: "A list of key references, including to other software addressing related needs. Note that the references should include full names of venues, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline."

**Comment by egpbos** [comment]
The README also currently contains (under "Why DIANNA?") a couple of [xx] reference numbers that were probably copy-pasted from another document. These should either be removed or given links to the references section that is to be added.

**Comment by gcroci2** [comment]
I added references section at the bottom of the .md file (see https://hackmd.io/@gcroci2/BywaTzTJc/edit). I'm adding the references I'm using in the paper.bib file ([open PR #241](https://github.com/dianna-ai/dianna/pull/241)). Do we want to merge the PR at the end of the write and continue to commit to that branch?
