### ISSUE TITLE
readme/JOSS: add "acknowledgements" section

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#141]
JOSS needs a section acknowledging any financial support, which in this case was provided by the Center and SURF. Maybe, in the future, we will get other sponsors who want to be mentioned, so good to have it there already.

Also, we could acknowledge input from the people supplying the user stories.

**Comment by gcroci2** [comment]
I added Acknowledgements section (see https://hackmd.io/@gcroci2/BywaTzTJc/edit) and I wrote the draft of it mentioning Surf, eScience Center, and relevant python packages used by DIANNA.
