### ISSUE TITLE
readme: Add links to the respective notebooks in the table data and methods and links of methods' main paper

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#142]
Once they are done, probably.

Was there already something done in #113 @elboyran?

- [x] Links to ROADMAP.md for planned activities.
- [x] Add a sentence that the links to all supported methods and modalities are at the generic tutorial folder and provide a link.
- [x] Links to methods papers (in the table header).

**Comment by elboyran** [comment]
Solved in #164
