### ISSUE TITLE
readme: Add informative screen shots

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#143]
Just above or below the DIANNA title

**Comment by egpbos** [comment]
Actually, this issue is unclear to me. Could someone describe what is needed here?

**Comment by elboyran** [comment]
I made the issue. I thought of putting the widget(whose prototype we've created some time ago) or at least an image of all methods heatmaps for an image (per dataset?) and a sentiment sentence. Something like the top image [here](https://github.com/albermax/innvestigate). 

Basically the functioning of DIANNA in a glance of an image.

**Comment by gcroci2** [comment]
I tried all methods with the leaf image and these are the best results I got:
LIME
![lime](https://user-images.githubusercontent.com/55382553/153176139-6b859adb-8c0f-4985-940d-582641d1ca47.png)
RISE
![rise](https://user-images.githubusercontent.com/55382553/153176143-5c062e39-911d-436e-98fe-906e1719216c.png)
KernelSHAP
![kernelshap](https://user-images.githubusercontent.com/55382553/153176146-ac7b0d6f-5f14-4f9e-abec-c8db67e4af06.png)

The results with the mnist dataset are much better, and I'll make a PR to edit the readme using those.
