### ISSUE TITLE
add readme in notebooks folder

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#148]
We should have a brief readme in the notebooks folder so users know how to use them.

**Comment by loostrum** [comment]
FYI I added a readme with method/modality table in the LIME on images PR, but no significant text.

**Comment by egpbos** [comment]
We can also put a Binder badge in there, see https://mybinder.org/v2/gh/dianna-ai/dianna/HEAD?labpath=tutorials

**Comment by egpbos** [comment]
#172

**Comment by elboyran** [comment]
All logos to be used in the tutorial and main READMEs are now on the [Sharepoint/Logos](https://nlesc.sharepoint.com/:f:/s/DIANNA/EjLIGLupByZJgs2w5nMSYiQByuRHX-AlSCaScZcCA-2u9w?e=968H4o)

**Comment by elboyran** [comment]
All logos to be used in the tutorial and main READMEs are now on the [Sharepoint/Logos](https://nlesc.sharepoint.com/:f:/s/DIANNA/EjLIGLupByZJgs2w5nMSYiQByuRHX-AlSCaScZcCA-2u9w?e=968H4o)
