### ISSUE TITLE
more basic tutorial notebooks?

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#149]
The GT suggested in #116 that we have more basic tutorial notebooks:

> [...] just give good titles, e.g., “Introduction to DIANNA” can be a tutorial, with an overview of everything; “Explainable AI using Tensorflow and DIANNA” can be a tutorial, more focused. “How to choose which DIANNA method to use” can go more to the point.

I'm not sure about how this would work. It seems to make sense from a user perspective, though, so let's discuss.

**Comment by elboyran** [comment]
At least 1 basic and maybe 1 advanced generic tutorial notebooks.

**Comment by elboyran** [comment]
Blocking issue #196

**Comment by elboyran** [comment]
First the PR #223 should be resolved!
