### ISSUE TITLE
Update tutorial notebooks with direct data and model downloads (when possible)

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#171]
See Leon's nice tutorial on RFB case #707 on how to download directly from Zenodo. See also the _text in italics_ below.

### `tutorials`

├── README.md
├── conversion_onnx
│   ├── ...
├── overview.ipynb
└── explainers
    ├── KernelSHAP
    │   ├── kernelshap_geometric_shapes.ipynb
    │   ├── kernelshap_mnist.ipynb
    │   ├── kernelshap_tabular_penguin.ipynb
    │   └── kernelshap_tabular_weather.ipynb
    ├── LIME
    │   ├── lime_images.ipynb
    │   ├── lime_tabular_penguin.ipynb
    │   ├── lime_tabular_weather.ipynb
    │   ├── lime_text.ipynb
    │   ├── lime_timeseries_coffee.ipynb
    │   └── lime_timeseries_weather.ipynb
    └── RISE
        ├── rise_imagenet.ipynb
        ├── rise_mnist.ipynb
        ├── rise_text.ipynb
        └── rise_timeseries_weather.ipynb
        └── rise_timeseries_frb.ipynb (already model downloaded, not by pooch)

Zenodo links per tutorial:

### Generic

- [x] overview.ipynb : data available only locally | [text ONNX model](https://zenodo.org/records/5910598)|  [TS regression ONNX model](https://zenodo.org/records/10580833)| ~~[binary MNIST onnx model](https://zenodo.org/record/5907177)~~ The model variant used in tutorial is with TF int he name, otherwise the one from zenodo gives an TF error...

### KernelSHAP

- [ ] kernelshap_geometric_shapes.ipynb: [shape data](https://doi.org/10.5281/zenodo.5012824) | [onnx model](https://zenodo.org/records/5907059)
- [ ] kernelshap_mnist.ipynb: data available only locally | [onnx model](https://zenodo.org/record/5907177)
- [ ] kernelshap_tabular_penguin.ipynb: data already downloaded from SNS | [onnx model class.](https://zenodo.org/records/10580743)
- [ ]  kernelshap_tabular_weather.ipynb: data already downloaded from Zenodo using pandas, try pooch | [onnx model regr.](https://zenodo.org/records/10580833)

### LIME

- [ ] lime_images.ipynb: example image is local | [onnx model](https://zenodo.org/record/5907196)
- [ ] lime_tabular_penguin.ipynb: see kernelshap_tabular_penguin.ipynb above
- [ ] lime_tabular_weather.ipynb see kernelshap_tabular_weather.ipynb above
- [ ] lime_text.ipynb: the word vectors are only local | [onnx model](https://zenodo.org/record/5910598)
- [ ] lime_timeseries_coffee.ipynb: might be easier to load locally the data and labels compared to from the [source](https://timeseriesclassification.com/description.php?Dataset=Coffee) | [onnx model](https://zenodo.org/records/10579458) 
- [ ] lime_timeseries_weather.ipynb data generated in the notebook or _already downloaded from Zenodo or read locally_ | [onnx model](https://zenodo.org/record/7525955)

###  RISE

- [ ] ~~rise_imagenet.ipynb: example image is local | model loaded from TF~~
- [ ] rise_mnist.ipynb: see kernelshap_mnist.ipynb above
- [ ] rise_text.ipynb: see  lime_text.ipynb above
- [ ] rise_timeseries_weather.ipynb: see lime_timeseries_weather.ipynb above

**Comment by loostrum** [comment]
Perhaps we can use the [pooch](https://pypi.org/project/pooch/) library to simplify this

**Comment by elboyran** [comment]
@loostrum, do you mind if I make (in the ever growing #776) the RFB model being downloaded under `models` folder, not in the same folder as the tutorial?
I refer to the `# Download model from zenodo` cell at the beginning of [rise_rimeseries_frb.ipynb](https://github.com/dianna-ai/dianna/blob/main/tutorials/explainers/RISE/rise_timeseries_frb.ipynb).

**Comment by elboyran** [comment]
> @loostrum, do you mind if I make (in the ever growing #776) the RFB model being downloaded under `models` folder, not in the same folder as the tutorial? I refer to the `# Download model from zenodo` cell at the beginning of [rise_rimeseries_frb.ipynb](https://github.com/dianna-ai/dianna/blob/main/tutorials/explainers/RISE/rise_timeseries_frb.ipynb).

done by https://github.com/dianna-ai/dianna/pull/776/commits/faf3c4f8ec7080dedff48ac61812ad6864a73710

**Comment by loostrum** [comment]
That won't work if dianna is installed system-wide though, what is the objection to downloading it to the local folder?

**Comment by elboyran** [comment]
What do you mean bu installed system-wide? Why wouldn't it work, if we still use the root_dir?
As for the reasoning - it looks a bit confusing that all other tutorial models are under `models`' folder and this one ends up along with all RISE tutorials.

**Comment by loostrum** [comment]
Effectively I mean that it fails when the user that installed dianna is not the same user that runs the notebooks. As a concrete example we pre-installed dianna at the AI4S2S workshop. The participants would not have write acces to the root_dir.
In general I'm not sure it's a good idea to download things to the install folder, I'm not sure if those downloaded files are removed when someone later uninstalls dianna (which they shouldn't, of course ;-) )

**Comment by elboyran** [comment]
> Perhaps we can use the [pooch](https://pypi.org/project/pooch/) library to simplify this
Didn't understand how to get the hash.

**Comment by elboyran** [comment]
For the overview notebook, it's been addressed in

**Comment by loostrum** [comment]
> > Perhaps we can use the [pooch](https://pypi.org/project/pooch/) library to simplify this
> > Didn't understand how to get the hash.

The hash is a hash of the file, e.g. a MD5 of SHA256 hash. It's probably easiest to get with pooch itself, see this part of the documentation of `pooch.retrieve`:

    You can bypass these checks by passing ``known_hash=None``. If this is
    done, the SHA256 hash of the downloaded file will be logged to the screen.
    It is highly recommended that you copy and paste this hash as *known_hash*
    so that future downloads are guaranteed to be the exact same file. This is
    crucial for reproducible computations.

**Comment by loostrum** [comment]
@elboyran Nice that it's fixed in the overview notebook! Shall I pick it up for the other notebooks?

**Comment by elboyran** [comment]
@loostrum , please, go ahead!
