### ISSUE TITLE
Find md editor to colloborate easily on MD paper

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#181]

**Comment by loostrum** [comment]
For the workshops we use http://hackmd.io/. It's quite nice, but sometimes lags a bit and starts messing up text when many (>15) people are working in it at the same time.

**Comment by elboyran** [comment]
This [blog post](https://techwiser.com/online-markdown-editor) puts [socraties.io ](http://socrates.io/) on the top of the list.

**Comment by gcroci2** [comment]
I can't access socrates.io! Could somebody else try it?
If it doens't work, I propose to use hackmd, which you already know and is the second on the blog post list.

**Comment by loostrum** [comment]
It doesn't work for me either. With the website apparently gone, and the
latest commit on their Github 9 years ago, I think it's safe to assume it
won't come back. I'd vote for HackMD in that case as well

**Comment by elboyran** [comment]
@gcroci2 , did you try [hackmd](https://hackmd.io/#)?

**Comment by gcroci2** [comment]
I tried HackMD as well and I think it's nice that you can link Github repo and that it comes with a side preview like overleaf, and we could make useful use of the comments while drafting. So I give it my vote too :)

**Comment by cwmeijer** [comment]
we chose hackmd

**Comment by gcroci2** [comment]
link to edit paper.md: https://hackmd.io/@gcroci2/BywaTzTJc/edit

**Comment by loostrum** [comment]
I think _anyone_ that is signed in to hackmd can edit the paper with that link, could anyone confirm if that is indeed the case?
The chances of misuse are probably slim, but perhaps we don't want to post the link publicly

**Comment by gcroci2** [comment]
> https://hackmd.io/@gcroci2/BywaTzTJc/edit

For now I changed the note permission to Owners, and I think only me/the owners of the repo can access. But definitely we should check this. Could someone help me check it out?
