### ISSUE TITLE
Create pitch slides for Dianna

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#183]

**Comment by egpbos** [comment]
They have been created. Where shall we store stuff like this?

**Comment by elboyran** [comment]
We have a [DIANNA team Sharepoint](https://nlesc.sharepoint.com/:f:/s/DIANNA/EhmWX_hLxMhDhcbp62y9Jc8BZ4O5RwKMZrtqwfQyIuPr2g?e=c8yiGN)

**Comment by elboyran** [comment]
I cannot find them, where exactly?

**Comment by egpbos** [comment]
Under presentations.

**Comment by elboyran** [comment]
OK, because I also had made a folder- pitches ;-) It's [there](https://nlesc.sharepoint.com/:f:/s/DIANNA/ElWZZ3HrGLJLqmapGfn6NkoB7H8QiUgkvJ-Kt13mSPeqHg?e=JcbD1V) now.

**Comment by egpbos** [comment]
Ah haha great, missed that one.

**Comment by elboyran** [comment]
BTW the project started on 1 March 2021 ;-)

**Comment by egpbos** [comment]
Ah ok, edited that, thanks. If you have other suggestions, let us know via Teams, the pitch is tomorrow between 10 and 11, so not much time to update the slides, but we can add it afterwards for future pitches.
