### ISSUE TITLE
Improve explanation results in the tutorial notebooks of RISE text

### ISSUE THREAD

**Issue by gcroci2** [dianna-ai/dianna#206]
Results from rise_text.ipynb:
<img width="1137" alt="Screenshot 2022-02-08 at 12 07 05" src="https://user-images.githubusercontent.com/55382553/152975652-74f9f15b-0704-4735-a934-87a2cc8c37a9.png">

Results from lime_text.ipynb:
<img width="1129" alt="Screenshot 2022-02-08 at 12 07 16" src="https://user-images.githubusercontent.com/55382553/152975662-b9a83e09-13aa-4119-be48-9059ffa0c0d3.png">

If you look at the values, results are actually similar in terms of scores, but the scores range is different. We need to figure out scores range and how this can be solved.

**Comment by elboyran** [comment]
@gcroci2 I do not get what you mean - I see different scores for the same words in both methods. It's been a while, but if you wish, could you,please, elaborate?

**Comment by gcroci2** [comment]
> @gcroci2 I do not get what you mean - I see different scores for the same words in both methods. It's been a while, but if you wish, could you,please, elaborate?

Since they are two different methods, the scores assigned in each of them may have a different range. When we plot the highlighted text, we do not normalize the two different ranges, so they are not really comparable, and also the plots can be more confusing. If for example Rise has a range between 0 and 1, and Lime has a range between 0 and 0.5, before plotting them we should use some normalization function to match the ranges. This is of course not needed if we're sure that both methods are giving scores using the same range (or domain).
