### ISSUE TITLE
Make plan/schedule for paper/report on medical usecase

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#229]

**Comment by elboyran** [comment]
email from 16 Feb 2021

Dear Elena,

Thank you for the reminder. This will be part of our next sprint, starting next week. Why don’t we do a first pass as soon as possible and share it with you? Depending on how you feel about it, we can add an interview layer to it to complement it. Sorry we’re using a bit of a “just-on-time” delivery approach here.

Regarding the JOSS submission, I’m happy to review the draft or add a little contribution on where such tools fit in a research pipeline if you think that would be useful.

Best regards,
Matthieu

**Comment by elboyran** [comment]
After some discussions of the possible options, we concluded that Mattiueu will add the report to Zenodo. By the end of the week, he will send us the first draft. Report is expected to be finished by the end of the month/sprint.

**Comment by elboyran** [comment]
The first draft of the [Medical Use Case (MUC)](https://nlesc.sharepoint.com/:b:/s/DIANNA/ERiOU3fcdetKtrU1zu2dnuoB3N2wwKIDsJKX5Pbh_NNVeg?e=gYnHdE) report is in Sharepoint.

**Comment by elboyran** [comment]
The final report has been updated in Sharepoint and published in [Zenodo](https://zenodo.org/record/6303282).
