### ISSUE TITLE
copy statement of need section

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#230]
get content from readme

**Comment by gcroci2** [comment]
I don't think there is a "statement of need" section in our readme (correct me if I am wrong), so I wrote a [draft](https://hackmd.io/@gcroci2/BywaTzTJc/edit) starting from our readme and the [usual example paper](https://joss.theoj.org/papers/10.21105/joss.03951).

**Comment by elboyran** [comment]
Indeed, there was no statement of need as such. It's good as a draft. Maybe we can expand it a bit with the needs of scientists later.
