### ISSUE TITLE
copy high level summary

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#231]
copy from readme

**Comment by elboyran** [comment]
Hm, logging in with my git account and authorizing hackmd,io still can't access it :-(

**Comment by elboyran** [comment]
The links seem connected to your accoung @gcroci2 , maybe we have to authorize us/share somehow?

**Comment by gcroci2** [comment]
> Hm, logging in with my git account and authorizing hackmd,io still can't access it :-(

Now at least @elboyran, @cwmeijer, @geek-yang and I should have access (text me if this is not true)

**Comment by elboyran** [comment]
Good first draft. Maybe we have to mention also supporting ONNX and scientific repeatability a bit.

**Comment by gcroci2** [comment]
> Good first draft. Maybe we have to mention also supporting ONNX and scientific repeatability a bit.

Just added ONNX reference, and rewritten summary a bit. About repeatability, what do you think is nice to add?

**Comment by elboyran** [comment]
> > Good first draft. Maybe we have to mention also supporting ONNX and scientific repeatability a bit.
> 
> Just added ONNX reference, and rewritten summary a bit. About repeatability, what do you think is nice to add?

Maybe 1 sentence after it saying how much ONNX can benefit repeatable science.
