### ISSUE TITLE
Figure out what to do for ICT open

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#233]

**Comment by egpbos** [comment]
At least gather the presentations by @geek-yang and @loostrum for the colloquium. Then perhaps see what we can reuse for the concrete conferences we will go to, like ICT Open, but also possibly PyData later on.

**Comment by elboyran** [comment]
Dear Elena,

Thank you kindly for your message. We are aiming to inform everyone on Wednesday 23rd February about whether their abstract is accepted and in which format.

Should you have any further questions, please do not hesitate to reach out.

Kind regards,
 
Elke Ballemans
Projectmanager
 
SPITZ congres en event – Lange Voorhout 1 – 2514 EA Den Haag
070 360 9794 | 06 31 97 47 63 | [www.spitz.nu](http://www.spitz.nu/)
Vrijdag afwezig

**Comment by elboyran** [comment]
> At least gather the presentations by @geek-yang and @loostrum for the colloquium. Then perhaps see what we can reuse for the concrete conferences we will go to, like ICT Open, but also possibly PyData later on.

The colloquium presentations are at [SharePoint/Presentations](https://nlesc.sharepoint.com/:f:/s/DIANNA/EpjPLKP1mmxIvGVe88xDSGMBLxhkomM_60zIwYl1M0_BiA?e=ycO3Si).

**Comment by elboyran** [comment]
**We got the demo. We should register ASAP.**

**Important dates and deadlines:**
•	Tuesday 1 March - the programme will be published on the website.
•	For demo's only Wednesday 9 March: Submit your logo and special requests for your demo stand

**Next steps
Demo stands**
To show your demo on the online platform, you have the option to upload a video pitch, but this is not mandatory. You may upload your pitch in 'my abstract'. Please note that the video pitch should be uploaded as an embed code. For an explanation on how to embed a video on youtube or Vimeo, please click [here](https://www.ictopen.nl/upload/files/Embedding%20a%20video(2).pdf). The pitch should be maximum 5 minutes. You can film the pitch through Zoom or Teams for example.
Your Demo stand at ICT.OPEN2022 consists of a high table with two chairs whether If you would like a screen (40" Full HD Screen) added to your stand, please let us know by Wednesday 9 March. We also offer you the possibility to print your logo on your demo table. The space on the table where the logo will be displayed, is 100x60cm (hxw). Please send your logo by Wednesday 9 March to [deborah@spitz.nu](http://deborah@spitz.nu/).

**Comment by elboyran** [comment]
The registration is not free. 

[](https://www.ictopen.nl/register/?speaker=da5ac95e86dec8b2383c7f12b3fb356a#)Presence at ICT.OPEN2022 *
On site at RAI Amsterdam
I will join the conference completely online

    Online conference fee € 15

 
Entry to ICT.OPEN2022 on April 6th and 7th. The program on April 6th will start late afternoon.
Including an overnight stay at Novotel Amsterdam City from 6th till 7th April.

    Master/bachelor (hbo) students: € 50 (twin room, roommate)
    PhD students and postdocs: € 100 (twin room, roommate)
    Tenure track, permanent staff and other: € 150 (single room)

Entry to ICT.OPEN2022 on April 7th.
No overnight stay included.

    Master/bachelor (hbo) students: € 35
    PhD students and postdocs: € 70
    Tenure track, permanent staff and other: € 105

Probably I cannot attend on the 6th, it's my parental day (Wed). If my husband is at the hospital then (might know only 2 weeks in advance), I might not be able to attend the 7th either. **I really hope at least 2 other people from the team can attend both days and that I can attend on the 7th.**

**Comment by elboyran** [comment]
I've sent some questions to the organizers- see email.
