### ISSUE TITLE
Tensorflow-addons are available as wheel

### ISSUE THREAD

**Issue by bencomp** [dianna-ai/dianna#245]
Tensorflow is moving fast. I noticed yesterday that (for Python 3.9) I didn't need to build Tensorflow-addons myself, like I had tried a few weeks ago. [Tensorflow-addons on PyPI](https://pypi.org/project/tensorflow-addons/#files) shows that there are wheels available for Apple ARM64.
This means the installation instructions for M1 Apple computers can again be updated.

**Comment by elboyran** [comment]
@cwmeijer, I don't see a PR related to the issue. How do you want it to be reviewed?

**Comment by egpbos** [comment]
> @cwmeijer, I don't see a PR related to the issue. How do you want it to be reviewed?

I was wondering the same 😄

**Comment by egpbos** [comment]
Ok, I see now that the readme was changed to refer to this issue. I think that solves this, so consider this my review. We can close imo. I will open a new issue to remind ourselves to remove the whole special section when it becomes completely irrelevant (I hope with the next tensorflow release).

**Comment by egpbos** [comment]
See  #268
