### ISSUE TITLE
JOSS: Make the text in the paper uniform

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#246]
Make sure it reads well.
Make sure we are consistent in our use of abbreviations and make sure they are all explained exactly once in the paper.

**Comment by gcroci2** [comment]
I have uniformed the various sections, corrected typos, added citations and links, and integrated useful comments from Matthieu. I think the best would be for at least one other person to go through the paper again.

**Comment by elboyran** [comment]
I left some comments. 

Probably can improve the text further given the time.
I will make a new issue for that as well as final check if it fits the JOSS criteria. 
Also one for compiling and testing the process.
