### ISSUE TITLE
ICT.open: prepare easy file transfer to our machine

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#247]
I think we want our demo to support models, text and images from the audience. We probably need to prepare a simple solution to transfer the files to the notebook or vice versa etc.
some options:
- usb drive (this is the worst solution imo)
- some drop box/surfdrive option
- email
- bluetooth file transfer

**Comment by loostrum** [comment]
ICT open is well in the past now, this issue is no longer relevant.
