### ISSUE TITLE
ICT.open: create video of demo

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#249]
"To show your demo on the online platform, you have the option to upload a video pitch, but this is not mandatory. You may upload your pitch in 'my abstract'. Please note that the video pitch should be uploaded as an embed code. For an explanation on how to embed a video on youtube or Vimeo, please click [here](https://www.ictopen.nl/upload/files/Embedding%20a%20video(2).pdf). The pitch should be maximum 5 minutes. You can film the pitch through Zoom or Teams for example."
First decide if we actually want to make a video as it's not mandatory.

**Comment by gcroci2** [comment]
Uploaded mp4 demo video on Teams, waiting for feedback :)

**Comment by elboyran** [comment]
I also wrote this in Teams:

> @gcroci2, It is really nice! I wonder if at the beginning we might mention some of t he USP (Unique selling points), e.g. or the Key features the JOSS paper) before going into the details. Or at the end. But the rest is so nice and smooth, maybe only if you can easily edit by adding few seconds at the end before the last sentence. Otherwise- it's pretty good as it is.

**Comment by gcroci2** [comment]
> I also wrote this in Teams:
> 
> > @gcroci2, It is really nice! I wonder if at the beginning we might mention some of t he USP (Unique selling points), e.g. or the Key features the JOSS paper) before going into the details. Or at the end. But the rest is so nice and smooth, maybe only if you can easily edit by adding few seconds at the end before the last sentence. Otherwise- it's pretty good as it is.

I just updated the demo video, it's in Teams chat

**Comment by elboyran** [comment]
I like it!

**Comment by elboyran** [comment]
Submitted to [ICT Open program page](https://www.ictopen.nl/programmaonderdelen/sessie/6227f406/).
