### ISSUE TITLE
Create notebook for the demo

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#250]
The notebook should contain multiple XAI methods
Maybe 2 notebooks for text and images?

**Comment by gcroci2** [comment]
Notebook `demo.ipynb` is in [this](https://github.com/dianna-ai/dianna/tree/249_demo) branch, in the tutorials folder. Should we merge this branch with main?

Also, we're having problems with LIME, so I am not sure about including it in the demo notebook (the results do not make sense).

**Comment by gcroci2** [comment]
After this morning's meeting we decided to leave binary mnist example even for LIME method, which will be fixed soon
