### ISSUE TITLE
Register for ICT.open

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#251]
Register for yourself and post a comment here

**Comment by elboyran** [comment]
Just registered for 7 April. With the rate of EUR105.
(Waiting for the response of whether the rest of  you can pay less...)

**Comment by cwmeijer** [comment]
I have trouble registering:
When I try to register through their site, it says my email is already in use. When I try to register through the personal link in the mail they sent me, I just get logged in and I see no registration options. It actually kind of looks like I'm already registered.
If anyone has the same, please let me know.

**Comment by gcroci2** [comment]
I did it, and I paid the 105 euros registration fee.

**Comment by egpbos** [comment]
I registered for online attendance.

**Comment by cwmeijer** [comment]
Registered and paid (105 euro).
