### ISSUE TITLE
Make LIME work (again) with binary mnist

### ISSUE THREAD

**Issue by gcroci2** [dianna-ai/dianna#254]
Data I used are `binary-mnist.npz`, and the model is `mnist_model_tf.onnx`. See the [demo.ipynb](https://github.com/dianna-ai/dianna/blob/main/tutorials/demo.ipynb) file. 

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/55382553/156757238-504f8413-37fc-4faf-9f8a-c960ccfde8cb.png">

LIME seems to be "broken" and it outputs all ones for this binary mnist image. BUT when I did this weeks ago, I obtained this nice one for the readme:

<img width="182" alt="image" src="https://user-images.githubusercontent.com/55382553/156757551-14168200-3fa1-4c3b-a1d6-d1578f9b3f84.png">

It's not clear if it's LIME itself or @loostrum fix to the grayscale images, but I also tried to add the channels and reproduce what I did the first time, before his fix, and it didn't worked as well.

**Comment by egpbos** [comment]
After having confirmed that LIME still works (see #208), maybe it could help to take a look here: https://github.com/marcotcr/lime/blob/master/doc/notebooks/Tutorial%20-%20MNIST%20and%20RF.ipynb

**Comment by egpbos** [comment]
The PR from @loostrum you mean is #215, right?

**Comment by egpbos** [comment]
Tried out reverting to the repo's state from before #215 in #271: didn't work, still only 1's. Seems like it wasn't our doing then (or at least not our doing in that PR).

**Comment by egpbos** [comment]
For reference, this is the commit where apparently things were still working: https://github.com/dianna-ai/dianna/commit/66ed07ca0d067c0286ae4ca8851b99c58418dba9. It was added in #214, so indeed one before #215. @gcroci2, were you using the master version at that time, or some slightly earlier version? In the latter case, we can still try reverting some other changes between when you used it and #215.

**Comment by egpbos** [comment]
#272 reverts the repo to the state of Feb 1st. The demo notebook still only gives ones for LIME. @gcroci2, were you already working with DIANNA before Feb 1st? If not, the this should exclude the possibility that it was something we changed in DIANNA that broke LIME.

**Comment by gcroci2** [comment]
> For reference, this is the commit where apparently things were still working: [66ed07c](https://github.com/dianna-ai/dianna/commit/66ed07ca0d067c0286ae4ca8851b99c58418dba9). It was added in #214, so indeed one before #215. @gcroci2, were you using the master version at that time, or some slightly earlier version? In the latter case, we can still try reverting some other changes between when you used it and #215.

I am pretty sure I was using the master version, and I installed DIANNA running `python3 -m pip install git+https://github.com/dianna-ai/dianna.git`

**Comment by egpbos** [comment]
Ok, so then something else must have changed. Do you happen to have the code still that you used to create the screenshot in the README?

**Comment by gcroci2** [comment]
> 

I was looking for it when this issue started. Unfortunately, when I created the screenshot I was still organizing my desktop and decided to delete that local version and just cloned the repo again. So the answer is no :(

**Comment by egpbos** [comment]
Hypothesis: the model only predicts ones, and not zeros, meaning that when you get a zero the whole explanation map should be empty.

Test: try with a one.

Result: nope.

![Schermafbeelding 2022-03-22 om 09 31 11](https://user-images.githubusercontent.com/6146598/159439361-5e232ac4-e896-4fb6-9cf9-04dc42b0db87.png)

**Comment by egpbos** [comment]
Hypothesis: the mnist_tf model isn't working, maybe @gcroci2 used the other mnist model for the screenshot.

Test: modify the demo to use the other mnist model.

Result: nope.
![Schermafbeelding 2022-03-22 om 09 46 42](https://user-images.githubusercontent.com/6146598/159441987-759a9028-f91e-4c94-b0fc-e53add267943.png)

**Comment by egpbos** [comment]
Ok, I may be on to something: I think LIME expects 0-255 range values, whereas the notebook divides input by 256 to get 0-1, which the model expects. With 0-255 range values, at least the segmentation algorithm works again (it didn't segment anything with values between 0 and 1).
