### ISSUE TITLE
Refer to DIANNA on our Web site- where we focus

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#255]
If possible at the end of the AI Technology text @ https://www.esciencecenter.nl/where-we-focus/ai/

**Comment by elboyran** [comment]
Starting point: post on the [Corporate website Teams channel](https://teams.microsoft.com/l/channel/19%3a68f7cc6312c046d1be3dd2e89241a026%40thread.tacv2/Corporate%2520Website?groupId=f590bf84-dc28-405e-8486-eaf670134885&tenantId=aa3aeacc-6307-42b2-ac05-787dd5c32574)

**Comment by elboyran** [comment]
Posted on the channel:

> 
> Please, update the [Artificial Intelligence page](https://www.esciencecenter.nl/where-we-focus/ai/).
> 
> In the last sentence the text is "our mcfly project", but the link points to software.
> Please add the following sentence at the end;
> To learn more about our woek on Explainable AI for scientists read about our [dianna project](https://research-software-directory.org/projects/dianna)​​​​​​​/[software](https://research-software-directory.org/software/dianna).
> 
> The choice between project or software should be consistent with the choice above.

**Comment by cpranav93** [comment]
I see that the change has not yet been implemented on the AI website. Shall we keep this issue open until it is? 

Another option could be to contact communications directly to speed this up?

**Comment by elboyran** [comment]
I've pinged Veronica on the channel about it.

**Comment by elboyran** [comment]
My new suggestion to her: 


> **Learn more about how the eScience Center supports AI developers with [our mcfly software](https://www.research-software.nl/software/mcfly), a automatically finds neural network configuration for deep learning on time series. To learn more about our work on Explainable AI for scientists, read about our [DIANNA project](https://research-software-directory.org/projects/dianna) and user-friendly [software](https://research-software-directory.org/software/dianna).**

**Comment by elboyran** [comment]
Website is [updated](https://www.esciencecenter.nl/where-we-focus/ai/).
