### ISSUE TITLE
JOSS: final edits and checking the JOSS criteria.

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#256]

**Comment by gcroci2** [comment]
I just uniformed all the citations always using .bib entries. Just the Acknowledgement paragraph is left since I am not sure how to cite SURF and eScience Center (right now they have just the hyperlinks)

**Comment by elboyran** [comment]
I've edited the **State of the field** bullet points.
Considering now how to do that for the **Key Features** section too.

**Comment by elboyran** [comment]
Addressing the JOSS Substantial scholarly effort criterion "Total lines of code (LOC). Submissions under 1000 LOC will usually be flagged, those under 300 LOC will be desk rejected.", I've checked the LOC usimg [codetabs](https://codetabs.com/count-loc/count-loc-online.html):
![LOC](https://user-images.githubusercontent.com/3244249/158355640-2121a297-7ae7-487d-b2ec-27a963c0877a.png)


# Lines (largest sections from the pie chart):
Pytnon: 1020
Jupyter: 3516
Plain text: 27778

**Comment by elboyran** [comment]
JOSS criteria:
" The paper should be between 250-1000 words. Authors submitting papers significantly longer than 1000 words may be asked to reduce the length of their paper."

_MS Word_ (intermediate) count (without the references, title and authors): 1374. 

**When giving feedback/edits, please, consider deleting/shortening.**

**Comment by elboyran** [comment]
HackMD actually also gives word count (including title and authors list): **1196** currently. in Word: **1179**. Both without the actual References section, but with references within.

**Comment by egpbos** [comment]
I count 1170 now without references. We can trim a bit more, but perhaps we can also just submit and see what they say. I think the main "issue" lengthwise is that we spend a lot of time on the state of the field, which is actually not about DIANNA itself, but I think it's nevertheless a really nice contribution that could be useful to people, so I think the amount of words is justified.

**Comment by gcroci2** [comment]
> I count 1170 now without references. We can trim a bit more, but perhaps we can also just submit and see what they say. I think the main "issue" lengthwise is that we spend a lot of time on the state of the field, which is actually not about DIANNA itself, but I think it's nevertheless a really nice contribution that could be useful to people, so I think the amount of words is justified.

I agree, I'd try to submit and see what they say as well.
