### ISSUE TITLE
JOSS: refer to the blog and improve references

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#257]
Blog's [link](https://blog.esciencecenter.nl/how-to-find-your-artificial-intelligence-explainer-dbb1ac608009)
Cite properly once published. Refer to it at the [cite blog] spot in **Key Features section.**
Fix the XAI methods/libraries references- add names in front of the actually references.

**Comment by elboyran** [comment]
Related to the JOSS branch and the PR #266

**Comment by elboyran** [comment]
For some reason fair-software checks fail?

**Comment by elboyran** [comment]
The latest paper PDF is at the Artifacts @ https://github.com/dianna-ai/dianna/actions/runs/1998500232

**Comment by cwmeijer** [comment]
Didn't Yang write a part of the blog as well? Now the blog is cited as Ranguelova 2022. Maybe this is a consequence of Medium preferring 1 author (but who made them king?). Just checking if this is correct and exactly the way we want it.

**Comment by elboyran** [comment]
Yes, Yang wrote the draft of half of the blog. I did mention this explicitly in the Acknowledgements. The editors told me, the author is only one in Medium (not ideal!). And I had to edit the blog a lot, since the editors had lots of comments ;-)

**Comment by elboyran** [comment]
Adding Yang as a co-author.
