### ISSUE TITLE
Finalize and publish blog post about XAI method selection.

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#259]
Reflect the comments from Blogging.
Draft link: https://blog.esciencecenter.nl/how-to-find-your-artificial-intelligence-explainer-dbb1ac608009

**Comment by elboyran** [comment]
[@PabRod](https://github.com/PabRod) how does it work from now on? I reflect the comments (until when do they come) and then you are the one to publish when you consider ready?

**Comment by PabRod** [comment]
The editorial team will go back to you as soon as possible. We'll have a meeting later this week and your blog will be the number one element on our list.

**Comment by elboyran** [comment]
Edited a bit the text also reflecting comments until now:

- Reshaped and renamed the Selection section and added explanation on how we chose 18/36 evaluaiton criteria
- Fixed abbreviations
- Added link to the XAI fact sheet paper in the References
- Replaced Medium links to DIANNA team members with ORCID links

**Comment by PabRod** [comment]
I just made a couple of minor content-unrelated editions, mostly related to typos.

Regarding the logo, I think the simpler one, without the eScience Center logo on top of it, is much better.

**Comment by PabRod** [comment]
Hi @elboyran. Please add [@liekelotte](https://github.com/liekelotte) to this conversation. She and I are going to do most of the editing.

**Comment by elboyran** [comment]
Hi @PabRod, how do I add her? As Assignee?

**Comment by elboyran** [comment]
> Hi @PabRod, how do I add @liekelotte? As Assignee?

No idea why assigning does not work, can't find her in the list and typing doesn't seem to help, wierd.

**Comment by elboyran** [comment]
I'll send her the link to this and maybe if she comments, she gets included in the short Suggestions list.

**Comment by elboyran** [comment]
Yay, that worked, now I could assign you to this issue ;-). @PabRod , @liekelotte , do you make moreiteraitons after I respond/address your comments or it is this once?

**Comment by liekelotte** [comment]
I've finished going through it now! Let me know if you would like more clarifications anywhere.

**Comment by elboyran** [comment]
Hi @liekelotte , thanks a lot, it made me realize it's not as clear to a non-expert as I hoped. I have addressed your comments, though not always following your suggestions. I hope it is clearer now?
@PabRod, @liekelotte , how shall I acknowledge your help? For now I've added your names in the **Acknowledgements** section (for that I need your **ORCID's IDs** to be consistent). Is this the way?

**Comment by PabRod** [comment]
Thanks a lot!

I really appreciate that you want to acknowledge us. My orcid is available on my [Github profile page](https://github.com/PabRod).

**Comment by elboyran** [comment]
> Thanks a lot!
> 
> I really appreciate that you want to acknowledge us. My orcid is available on my [Github profile page](https://github.com/PabRod).
> 
> I copypaste it here for your convenience: 0000-0002-2855-940X

Wow, amazing git profile page!

**Comment by elboyran** [comment]
@PabRod , @liekelotte , I've addressed your comments.

**Comment by PabRod** [comment]
We'll have an editorial board meeting tomorrow. We'll be back to you asap 😊

**Comment by liekelotte** [comment]
I've also added this subtitle right below the title, so people will know what to expect:

Our easy-to-use [DIANNA](https://github.com/dianna-ai/dianna) library helps you figure out which method works for your research.

Let me know if you think that's okay, too.

**Comment by elboyran** [comment]
> I've also added this subtitle right below the title, so people will know what to expect:
> 
> Our easy-to-use [DIANNA](https://github.com/dianna-ai/dianna) library helps you figure out which method works for your research.
> 
> Let me know if you think that's okay, too.

@liekelotte , yes, it's nice a have an "advertising subtitle"!

**Comment by liekelotte** [comment]
@elboyran We will publish the blog post tomorrow. 

Could you 

- Compose a tweet that we can post together with the blog?
- Double check that every author's social media handle / website is linked in the way they want?

**Comment by elboyran** [comment]
Hi @liekelotte,

- I do not use Tweeter, so am not sure what is a good tweet. Is this OK?

> [DIANNA](https://github.com/dianna-ai/dianna) (Deep Insight and Neural Network Analysis) will help you find the best AI eXplainer (XAI) for your research data problem even if you are not an (X)AI expert! This blog explains how.DIANNA (Deep Insight and Neural Network Analysis) will help you find the best AI eXplainer (XAI) for your research data problem even if you are not an (X)AI expert! This [blog](https://blog.esciencecenter.nl/how-to-find-your-artificial-intelligence-explainer-dbb1ac608009) explains how.
With the correct blog link, of course.
- The authors/acknowledged people wanted their ORCID id. I'm only missing yours.

**Comment by liekelotte** [comment]
This is great! I'll link my own, thanks!

**Comment by elboyran** [comment]
The [blog](https://blog.esciencecenter.nl/how-to-find-your-artificial-intelligence-explainer-dbb1ac608009) has been published!

**Comment by PabRod** [comment]
Thank you everyone for the great work. It was really nice collaborating with you. I am particularly impressed by your fast and efficient reactions.

Looking forward for doing it again! :+1:

**Comment by liekelotte** [comment]
Hi Elena! I realised I have one additional request after reading your blog again: I think it would be really nice if below the figure with the explanation (red and blue pixels), you describe what blue and red means. Right now, it's not actually clear what the explanation demonstrates, and I think stating that it shows what the algorithm pays attention to makes the whole point of the blog clearer. Would you be able to add a sentence there?

**Comment by liekelotte** [comment]
Sorry to only realise after publishing! luckily Medium lets you edit published posts as well :)

**Comment by elboyran** [comment]
I'll try to edit now.

**Comment by elboyran** [comment]
I've updated the figure caption.
