### ISSUE TITLE
Dependencies list missing

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#26]
When trying out the notebook at `example_data/xai_method_study/LRP/LRP_mnist_binary.ipynb`, two dependencies are missing: `torch` and `captum`. Probably, the same will go for some other notebooks. We should maybe add a requirements.txt at the top level for all dependencies, or add separate ones in each notebook directory with specific deps for those notebooks.

**Comment by geek-yang** [comment]
A requirements.txt at the top level for all dependencies is added after checking all the notebooks in the folder "example_data".

Check this PR in the repo dianna-exploration: https://github.com/dianna-ai/dianna-exploration/pull/145
