### ISSUE TITLE
JOSS: check the paper compiles

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#266]
https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles

**Comment by elboyran** [comment]
[GitHub Action](https://joss.readthedocs.io/en/latest/submitting.html#github-action)

If you’re using GitHub for your repository, you can use the [Open Journals GitHub Action](https://github.com/marketplace/actions/open-journals-pdf-generator) to automatically compile your paper each time you update your repository.

The PDF is available via the Actions tab in your project and click on the latest workflow run. The zip archive file (including the paper.pdf) is listed in the run’s Artifacts section.

**Comment by elboyran** [comment]
Don't understand why only the first batch of bullet point compile well, but not the rest?
The [paper.md](https://github.com/dianna-ai/dianna/blob/JOSS-paper/paper/paper.md) from the JOSS paper branch is exact copy of the one on[ HackMD](https://hackmd.io/@gcroci2/BywaTzTJc/edit). Looks fine on both github preview and HackMD, but not in the [resulting PDF](https://github.com/dianna-ai/dianna/actions/runs/1987689089).

There are other issues with the PDF to be discussed too:

- too large DIANNA logo- is fixable, but not sure if centered figure is OK
- Very ugly footnotes in the author's list, do we keep them?

**Comment by egpbos** [comment]
I'm trying to fix them by adding dates to the bib.

**Comment by egpbos** [comment]
Dates fixed.

**Comment by elboyran** [comment]
> Reply to @elboyran:
> 
>     * Big logo is fine imho. Actually, I would place it on the front page, but I leave that up to you.
> 
>     * Ok, let's remove.
> 
>     * We merge when the paper is done, I'd say. That's also a prerequisite for submission. I linked the PR to this issue.

Actually I'm not sure it's very informative. My latest idea: I want to put (after edit and embed the logo) the block diagram there.
![Architecture_high_level_resized](https://user-images.githubusercontent.com/3244249/158767983-5afe4531-7279-421a-a5e9-e1d5e3bedf68.png)

**Comment by elboyran** [comment]
Here's the figure I included:
![Architecture_high_level_with_logo](https://user-images.githubusercontent.com/3244249/158772917-920c40d9-dc26-43bf-9207-d64a6d92d724.png)

**Comment by elboyran** [comment]
Latest [PDF of the paper](https://github.com/dianna-ai/dianna/actions/runs/1997526034): see the Artifacts below.

Remaining questions for the stand-up:
- Do we merge the [JOSS paper branch](https://github.com/dianna-ai/dianna/tree/JOSS-paper) to main?
- Do we add Rena as co-author?

**Comment by cwmeijer** [comment]
- Yes, merge the branch. The fewer branches the better. I don't see any reason for this branch to exist after completion of the paper.
- I don't think so, assuming I didn't forget some contribution of hers.

I like the image that you included. A relatively subtle way to show our logo, but as it's the only figure, it won't be overlooked. Really nice.

**Comment by elboyran** [comment]
>     * I don't think so, assuming I didn't forget some contribution of hers.

What triggered me was the name of Damian included in the SURF part of the team. He didn't work on the project nor the paper at all after the approval and before Mattiuew joined. His name is as co-PI in the proposal and we had some meetings about the proposal and he gave me feedback then. Maybe he also contributed to the medical use case, I don't know, his name is on that report too. So, if Damian is in the paper, why not Rena- she did something for the running of the project?

**Comment by elboyran** [comment]
Rena has made some comments which I will address.
