### ISSUE TITLE
Hardcode labels for mnist and imagenet in dashboard

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#282]

**Comment by elboyran** [comment]
[Imagenet 1000 labels file](https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a)

**Comment by elboyran** [comment]
See our RISE [Imagenet tutorial](https://github.com/dianna-ai/dianna/blob/main/tutorials/rise_imagenet.ipynb)

**Comment by gcroci2** [comment]
Labels for binary mnist are hardcoded now (https://github.com/dianna-ai/dianna/tree/252_dashboard/dashboard).
