### ISSUE TITLE
Investigate requirements for supporting MXNet to ONNX conversion

### ISSUE THREAD

**Issue by loostrum** [dianna-ai/dianna#29]
An MXNet to ONNX convertor exists as part of the MXNet package, but generates invalid ONNX models in some cases. See also dianna-ai/dianna-exploration#5.

What would be required to support MXNet to ONNX conversion in DIANNA?

**Comment by elboyran** [comment]
Will not support MXNet with tutorial. People should figure it out from MXNet directly.
