### ISSUE TITLE
DIANNA 2 KD template

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#299]
Fill in the proposed template with content about DIANNA 2 application

**Comment by elboyran** [comment]
The DIANNA2 Proposal using the Draft KD template is on [DIANNA's Sharepoint](https://nlesc.sharepoint.com/:w:/s/DIANNA/EepG1_wW-K5FgX2-Ji3QGEkBWRWBJHz0-E17ZXGo5mW3RQ?e=QrfNwW)

**Comment by elboyran** [comment]
Rob had made a final template and published it to all. Copy of the template is on [DIANNA's Sharepoint](url).

**Comment by elboyran** [comment]
Proposal [link](https://nlesc.sharepoint.com/:w:/s/DIANNA/EZKrJgvq7kNKsWele97ZiYgB7qp9yXAskx7OLI2BXMs97A?e=QcljA8)

**Comment by elboyran** [comment]
Submitted. PDF version [link](https://nlesc.sharepoint.com/:b:/s/DIANNA/Ea0bdkkKs3BIgJmb9mlQ5_AByawwIXzFtIGK7MANkfwuTw?e=jzaIkk).
