### ISSUE TITLE
Compatibility spacy and numpy

### ISSUE THREAD

**Issue by APJansen** [dianna-ai/dianna#300]
On importing spacy I get the error:

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

I cloned the repo, installed through pip install -e . inside a new conda environment, got several errors from other packages which I installed using conda, and finally end up with this error.

Tried updating numpy but that didn't help

**Comment by APJansen** [comment]
Following this https://stackoverflow.com/a/69528768/14182162 with

pip uninstall spacy
pip install spcy --no-binary spacy

also didn't help

**Comment by APJansen** [comment]
This is what fixed it (thanks @egpbos):

conda create -n dianna python=3.9.12
conda activate dianna
conda install -c apple tensorflow-deps -y
python -m pip install tensorflow-macos
pip install tensorflow-metal
conda install onnxruntime
pip install -e .\[dev\]
conda install thinc
conda install spacy

@gcroci2 since you also have an M1 mac did you run into the same issues?

**Comment by gcroci2** [comment]
> This is what fixed it (thanks @egpbos):
> 
> conda create -n dianna python=3.9.12 conda activate dianna conda install -c apple tensorflow-deps -y python -m pip install tensorflow-macos pip install tensorflow-metal conda install onnxruntime pip install -e .[dev] conda install thinc conda install spacy
> 
> @gcroci2 since you also have an M1 mac did you run into the same issues?

I didn't have problems with spacy, but I was having problems with some of the dependencies using a conda env with python 3.8. Creating a new env with python 3.9 and manually installing tensorflow at that time solved the issues.

**Comment by loostrum** [comment]
Closing this issue as things seem to be resolved.
