### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#338]

**Comment by loostrum** [comment]
Version number updated to 0.5.0
Aron added as author
Manually triggered the release workflow to upload to test-pypi, which passed.
ToDo: verify that the test-pypi build works, and includes all files (e.g. non-python dashboard files may still need to be added to `MANIFEST.in`)

**Comment by loostrum** [comment]
The dashboard is not part of the python package at all.
Perhaps this is ok? It can only be run from the source directory anyway, which is a bit awkward if it's installed in the typical site-packages folder.

The dianna package itself does work fine on test pypi, so ready for release if the dasboard can be omitted.

**Comment by loostrum** [comment]
At standup we decided that the dashboard should not be part of the package for now. [A new issue](356) was opened to add it in the future.

**Comment by loostrum** [comment]
Release is ready when the CI finishes running. For the reviewer of this issue: please check that `pip install` properly installs the latest version for you :)

**Comment by cwmeijer** [comment]
I got some problems with torchtext missing when trying to import dianna after installation. I made an issue to solve later. After installing torchtext, dianna was imported just fine. This can be closed and moved to done.
