### ISSUE TITLE
Make movie reviews model easier to run

### ISSUE THREAD

**Issue by loostrum** [dianna-ai/dianna#34]
Currently it needs quite a lof of code to run; most of that can be made part of the model itself.
This would allow for easy use of the model in tests as well

**Comment by loostrum** [comment]
The input to the model should remain tokenized text, but the functions to create those from the input string will be made part of the model. The goal is to avoid having to define a lot of boilerplate code in the dianna repository just to be able to run the model.

**Comment by loostrum** [comment]
Draft PR in the exploration repo: https://github.com/dianna-ai/dianna-exploration/pull/147
The pytorch model is working, but after conversion to onnx it fails because there are no inputs.
Possibly related issue: https://github.com/pytorch/pytorch/issues/44299

**Comment by loostrum** [comment]
We will not use the simplified model as it doesn't work. This issue can be closed when the simplifications that don't affect the onnx model itself are merged in dianna-exploration.

**Comment by elboyran** [comment]
@loostrum could you, please, check if this can be closed?
