### ISSUE TITLE
Add lorentz input to sharepoint document

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#340]

**Comment by cwmeijer** [comment]
Blocked by #339

**Comment by elboyran** [comment]
Is not blocked. The document is already in [SharePoint](https://nlesc.sharepoint.com/:w:/s/DIANNA/EY4m-TgTyUpMomrw2zpg-84BE3OIZdSUC4GbSmpAteV5xg?e=Ww1TIQ).

**Comment by cwmeijer** [comment]
I added the input from my forms.

**Comment by loostrum** [comment]
I've added my forms as well.

**Comment by elboyran** [comment]
I've added mine as well. @loostrum did you put your in the shared file?
