### ISSUE TITLE
explore dashboard as it is

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#341]
result should give us:
tasks to refactor
tasks to fix certain parts of the dashboard
tasks for generalizing parts

**Comment by elboyran** [comment]
Here are some existing demonstrators for single XAI methods for inspiration.
[LRP](https://lrpserver.hhi.fraunhofer.de/) (my favorite)
[RISE](https://cs-people.bu.edu/vpetsiuk/rise/demo.html) (not so useful)
