### ISSUE TITLE
Investigate Lime suitability for time series

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#342]

**Comment by loostrum** [comment]
Potentially interesting: https://github.com/emanuel-metzenthin/Lime-For-Time

**Comment by cpranav93** [comment]
Investigated Lime-For-Time (https://github.com/emanuel-metzenthin/Lime-For-Time): It has two examples of time-series data-sets:
- coffee (http://timeseriesclassification.com/description.php?Dataset=Coffee) 
- ecg (http://timeseriesclassification.com/description.php?Dataset=CinCECGtorso)) 

The results for the coffee data-set seem interesting and meaningful while for the ecg, I am not sure if it is meaningful (need to look in to it further).
 
Also, the documentation is limited and there is no publication associated to the work (yet!). Could be interesting to pursue further if relevant.

**Comment by elboyran** [comment]
After searching for XAI methods for TS (see also issue #345), I found the following:

- [Presentation](https://www.gdria.fr/wp-content/uploads/2022/01/fromont.pdf) on the topic listing many methods, for post-hoc again CAM and LEFTIST.
-  Local Explainer For TIme Series classificaTion (LEFTIST) algorithm. It's an adaptation of LIME for TS. Still not clear whether the Lime-For-Time software implements that or imply makes original LIME run for TS. Unfortunately the LEFTIST paper ["Agnostic Local Explanation for Time Series Classification"](https://ieeexplore.ieee.org/document/8995349) is with limited access, couldn't find a free one. Anyone with free university account?
- Another LIME adaptation [LIMESegment](https://proceedings.mlr.press/v151/sivill22a.html) for TS was recently published [LIMESegment: Meaningful, Realistic Time Series Explanations](https://proceedings.mlr.press/v151/sivill22a/sivill22a.pdf)**with** [software](https://github.com/TortySivill/LIMESegment)! Worth investigating?

**Comment by loostrum** [comment]
We have a separate issues for comparing the different LIME-like implementations, but in any case there are implementations available that looks promising. Closing this issue.
