### ISSUE TITLE
Investigate kernelshap suitability for time series

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#343]

**Comment by geek-yang** [comment]
This [example](https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/model_agnostic/Multioutput%20Regression%20SHAP.html#Create-Multi-Output-Regression-Model) could be useful!

**Comment by geek-yang** [comment]
There is a question about the methods we want to support for timeseries in our package. Do we want to support multi-dimensional timeseries data, or just simple timeseries? In the current implementation of KernelSHAP, it supports 2D timeseries (with the shape [samples, features]). To extend it to handle more complex data, it is not that easy.

**Comment by loostrum** [comment]
Sounds good, closing this issue as we seem to have a reference for implementing support for the data type we want.
