### ISSUE TITLE
List ideas on how to use RISE for time series

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#344]
Ideas:
- Treat 1D multi-channel time series data as an image and use specific policies for masking. Options for masking policies:
  -  Mask only complete channels at the time. Like I did here: https://github.com/marpyr/Lorentz_workshop/blob/main/rise_timeseries/time_series_rise.ipynb
  - Or instead, mask only specific timesteps for all time-channels together. This would give you a relevance map of important time steps. This is tricky as some channels may be predictive for something earlier or later than other channels, making it inaccurate to attribute importance to single time steps. This would probably result in hard to interpret the resulting relevance maps.
  - Mask in superpixels (/blobs), like we do in the image case. The would need to look very different though because we need to make sure that super pixels are contained within a channel, or have the possibility to leak into all channels somehow instead of just their neighboring channels. The order of channels in the input format should have no effect on the XAI results.

What about spatio-temporal data? I need to think about this some more, feel free to add you ideas.

**Comment by cwmeijer** [comment]
For spatio-temporal data, I guess we could have options:
- Use masks like vanilla RISE, using the low res feature masks (or superpixels, or blobs) and use the same of those for every time step. This will result in an easy to interpret single saliency map aggregating all time steps.
- We could mask single time steps, like in the 1D example, ignoring the 'spatio' aspect of the spatio-temporal data.
- We could create 3D masks (superpixels/blobs in both spatial and temporal dimensions). This would draw from a very large population of possible 3D masks, which might introduce noise into the result if not enough masks are used. Also, visualizing the result will ask some creativity as the result will be 3D as well. Maybe some ideas from the voxel approaches from the chemistry branch of DIANNA development could be reused here (@APJansen)?

**Comment by cwmeijer** [comment]
Marked this ready for review because my ideas for 1D multichannel data support are in the opening comment of this issue. If anyone read them and they make sense, consider this issue reviewed and please close it in that case.
Also, feel free to comment with additional ideas regarding 1D multichannel support.

**Comment by loostrum** [comment]
Nice set of ideas, looks complete to me so I'll close this issue.

One thing to think about regarding this comment: "The order of channels in the input format should have no effect on the XAI results." I agree in case of independent channels, but in some types of data the channel order may have meaning in which case we might apply similar masking as in the image case.
