### ISSUE TITLE
Add dashboard to pip package

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#356]
Or make dashboard installable someway else.
Maybe it should get its own package or its subpackage like dianna[dashboard]

**Comment by stefsmeets** [comment]
#551 adds a cli command to start the dianna dashboard: `dianna-dashboard`

If we add the dashboard to the package resources, we can install it using `pip install dianna[dashboard], so that the dashboard works 'out-of-the-box'.
