### ISSUE TITLE
List differences between LIME variants

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#358]
What are the differences? Is useful code available for all of them? What are algorithmic differences?
- Lime-for-TS
- LEFTIST
- LIMESegment
Which one(s) should we pick to add to Dianna?

For links to papers and repos see issue #342 .

**Comment by elboyran** [comment]
> Also consult Sonja @sonjageorgievska on her experience with LIME for TS.

Her master student tried a package "made for LIME applied to time series", but no meaningful results were obtained in the SSI-ML Brugada syndrome project.

**Comment by elboyran** [comment]
Continuation in issue #369.
