### ISSUE TITLE
Implement DeepLiftSHAP for use with text

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#36]
Blocked by #56 
use
https://github.com/slundberg/shap

**Comment by geek-yang** [comment]
I explore `shap` for use with text by playing with the tutorial notebook "Keras LSTM for IMDB Sentiment Classification". But it doesn't work for me as there is a tensorflow/keras version related error. This error reveals that `shap` only supports tensorflow backend 1.x. It is not compatible with the latest version of tf/keras.  

It seems this error is well spotted by the users and there are two issues related to it (https://github.com/slundberg/shap/issues/1551 and https://github.com/slundberg/shap/issues/1456), but not fixed yet.

We need to further test it with our model when the onnx to tf converter is ready.

**Comment by geek-yang** [comment]
Two notebooks demonstrating `shap` for use with images work well for me ("[PyTorch Deep Explainer MNIST example](https://github.com/slundberg/shap/blob/master/notebooks/image_examples/image_classification/PyTorch%20Deep%20Explainer%20MNIST%20example.ipynb)" with pytorch model and "[Front Page DeepExplainer MNIST Example](https://github.com/slundberg/shap/blob/master/notebooks/image_examples/image_classification/Front%20Page%20DeepExplainer%20MNIST%20Example.ipynb)" with keras model).

**Comment by elboyran** [comment]
Not to support for now.
