### ISSUE TITLE
Determine label file format

### ISSUE THREAD

**Issue by cpranav93** [dianna-ai/dianna#360]
How can the user add labels to the dashboard? By uploading some file probably. Will that be csv or something else?
Recipe format or yaml or arff even?

This issue should result in a plan or design that can be implemented.

**Comment by laurasootes** [comment]
When this is implemented fix every mention of class_name_mnist and class_name_imagenet

**Comment by elboyran** [comment]
An illustration of how an ONNX model uses labels from an external TXT file is given in this [example notebook](https://github.com/elboyran/models/blob/leafsnap30-model/vision/classification/imagenet_inference.ipynb) from the ONNX model zoo: see section **Download label file for ImageNet**

**Comment by elboyran** [comment]
An [example notebook](https://github.com/dianna-ai/dianna/blob/main/tutorials/lime_images.ipynb) from our own repo uses labels in an external[ csv format file](https://github.com/dianna-ai/dianna/blob/main/tutorials/data/leafsnap_classes.csv).

**Comment by cpranav93** [comment]
Literature: 
I did a look through of existing data-sets and there is no real consensus on which format is ideal to go for in terms of label. The most common type is a .json that contains information on the full data-set (e.g. https://huggingface.co/datasets/glue/blob/main/dataset_infos.json) - the names of the labels/order is predefined in the data-set class. There are rare instances of python files that contain dictionaries (e.g. https://huggingface.co/datasets/imagenet-1k/blob/main/classes.py; or http://www.cs.toronto.edu/~kriz/cifar.html; or https://huggingface.co/datasets/Maysee/tiny-imagenet/blob/main/classes.py) - this seems to be the preferred method for image classification data-sets with large number of classes.  Other options include .txt files or .csv files - very uncommon in existing data-sets.

**Comment by cpranav93** [comment]
What do you mean by class numbers are not stored explicitly? Is it just a list of labels like:

dog
cat
flower

etc...
?

**Comment by loostrum** [comment]
Yes exactly. It should be a list of _all_ labels as well.

**Comment by cpranav93** [comment]
And is it in the order of classes? I.e dog is 0, cat is 1 etc in the model.

**Comment by loostrum** [comment]
Yep, is there another way you would have in mind? 
In the dashboard we could have it as an optional field. If the user doesn't provide labels, we use the numerical index. If they do, it's straightforward to get the label as string with this setup.

**Comment by cpranav93** [comment]
I think this is the best way for it now. The only niche case is when the user only wants specific labels but still has to input everything - this can be cumbersome when there are a lot of classes. I think we can stick with the txt file with all labels and adapt as the users need. If everyone agrees, we can close this issue.

**Comment by loostrum** [comment]
Yes we shortly talked about that niche case in the standup. Such a case would be at odds with displaying e.g. the top 5 classes in the dashboard. What if one of those 5 is not in the list of labels?
Let's close the issue, I think everyone is aware of the plan now.
