### ISSUE TITLE
Look into the data used by Mcfly

### ISSUE THREAD

**Issue by cpranav93** [dianna-ai/dianna#365]

**Comment by cwmeijer** [comment]
We used a subset of the PAMAP2 dataset for the mcfly tutorial and workshops. You can find more information about it in our issues about it: https://github.com/NLeSC/mcfly/issues?q=is%3Aissue+pamap2

- Earthquake prediction dataset
  - Multivariate timeseries dataset
  - Designed for tasks: classification
  - Link to the dataset: [PAMAP2](https://archive.ics.uci.edu/ml/datasets/PAMAP2+Physical+Activity+Monitoring)
  - Examples of model training recipe with this dataset: [mcfly tutorial](https://github.com/NLeSC/mcfly-tutorial/blob/master/notebooks/tutorial/tutorial.ipynb), [Kaggle](https://www.kaggle.com/code/avrahamcalev/time-series-models-pamap2-dataset)

We also wrote utils that would download (630MB) and preprocess the dataset. For its usage, see the mcfly tutorial above.

We could consider using PAMAP2 as an extra example, also given that the vastly different domain makes it a nice addition. The large download is a downside. Also see #364 .
