### ISSUE TITLE
Explore LIME for multivariate datasets.

### ISSUE THREAD

**Issue by cpranav93** [dianna-ai/dianna#366]

**Comment by cpranav93** [comment]
Talked to Sonja regarding her project with an MSc on XAI - they have not advanced further either. They are interested also in the concept of LimeSegment/LEFTIST. 

Found a possible paper that talks about multivariate time-series explanation with LIME: [Validation of XAI explanations for multivariate time series classification in the maritime domain - ScienceDirect](https://www.sciencedirect.com/science/article/abs/pii/S1877750321001976)

However, I do not have access to it through any of my channels - if someone can get access, please let me know. 

Lime can be effectively applied to univariate time-series with the existing methods ([LimeSegment ](https://github.com/TortySivill/LIMESegment) over LEFTIST?) and multi-variate time-series which have independent channels can also be treated separately as univariate time-series and can be handled by LimeSegment. The current state-of-the-art does not account for multivariate time-series with Lime as far as I was able to find.

**Comment by cpranav93** [comment]
From the paper: 
[Validation of XAI explanations for multivariate time series classification in the maritime domain](https://github.com/dianna-ai/dianna/files/9859904/1-s2.0-S1877750321001976-main.pdf), it appears that [LimeforTime](https://github.com/emanuel-metzenthin/Lime-For-Time) can be applied to multivariate time-series. It is not clearly explained as to how they get the contribution of different features but from an understanding of lime, it appears that they remove a feature to test how that affects the classification. 

From this, I think we can conclude that lime is a possible choice as an explainer for time-series (uni/multivariate). It is commonly used in a lot of the XAI papers involving time-series - however, the general conclusion of the papers tends towards the fact that LIME performance is not good.

**Comment by elboyran** [comment]
@cpranav93, given your research and the selected datasets (#364), what is our final conclusion- which LIME variant to use in DIANNA?

**Comment by cpranav93** [comment]
My conclusions:

1) Lime, especially as it is already a part of DIANNA, should be used for time series. Within that there are two sub-points:
- For univariate time-series - all existing methods can be used and are applicable. My conclusion would be to use LimeSegment as it is the current state-of-the-art and accounts for some of the failures of other methods
- For multivariate time-series - the paper cited above indicates that it is possible to do multivariate with lime in which case LimeSegment should also be capable for doing this. However, the methodology on how to do this is scant and we will have to decide how we proceed with this.

My conclusion is to use LimeSegment in Dianna for univariate TS for now before looking further. The authors of LimeSegment have indicated multivariate time-series as one of their future lines of research - we can always update as they update. Thoughts?
