### ISSUE TITLE
Add Leafsnap to ONNX model zoo.

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#370]
Replacing issue #368.

The submission should contain the following sections: 

- [x]  **Description**

- text
- ONNX checker

- [x] #390

- [x] #391

- [x] #392

- [x] #393

- [x]  **References**

- [x]  **Contributors**

- [x]  **License**

**Comment by elboyran** [comment]
To contribute a model to the ONNX model zoo one should follow the [How to contribute instructions](https://github.com/onnx/models/blob/main/contribute.md).

**Comment by elboyran** [comment]
Started composing the [LeafSnap30 contribution](https://github.com/elboyran/models/blob/leafsnap30-model/vision/classification/leafsnap30/README.md)

**Comment by elboyran** [comment]
Internal reviews could happen in another branch, namely [leafsnap](https://github.com/elboyran/models/tree/elboyran-leafsnap/vision/classification/leafsnap30)

**Comment by elboyran** [comment]
Our ONNX model (as published on[ Zenodo](https://zenodo.org/record/5907196)) has been verified against the latest onnx (v.1.12.0) checker.

**Comment by elboyran** [comment]
First [internal PR](https://github.com/elboyran/models/pull/1) submitted. Asked @cwmeijer for review.

**Comment by cwmeijer** [comment]
Great text! Approved!

I'm not so happy about this issue containing a long list of check boxes. It now is unclear what part is completely done and what part still needs a review. Of course I can see that in your PR, but still, it would be nicer to split some of it into separate tasks so they can end up in the Done column on the kanban board.

**Comment by elboyran** [comment]
Added some References, see the [PR](https://github.com/elboyran/models/pull/4). I suggested @geek-yang as reviewer.

**Comment by elboyran** [comment]
Added link to the model generation in  **More details** section, see [PR](https://github.com/elboyran/models/pull/5)

**Comment by elboyran** [comment]
The [PR ](https://github.com/onnx/models/pull/567) has problems due to unsigned commits! 👎 
try [fixing](https://github.com/onnx/models/pull/567/checks?check_run_id=10700528081) it by Checkout with [GitHib CLI](https://cli.github.com/)
![image](https://user-images.githubusercontent.com/3244249/212940661-a94193bb-500e-4565-bcd9-d27f70aa92ad.png)

**Comment by elboyran** [comment]
@loostrum I wonder if you can do something about your commits if it's in a fork of my repo...

**Comment by elboyran** [comment]
Make it ready for review as all commits have the 
![image](https://user-images.githubusercontent.com/3244249/215716079-ad1bee3b-7e92-427c-adf5-0f72233f4c75.png)
label. I have left this info in a comment. Lets see what the ONNX people say.

**Comment by elboyran** [comment]
I need some help with this one. When trying to git clone the onnx model repo (even only my branch) locally I get lfs issues, which I can't solve. I've worked exclusively on github on it and Leon did some commits 

But the ONNX repo complains the commits are not signed. See https://github.com/onnx/models/pull/567#pullrequestreview-1349434905 for the PR review and pointers to the solution isntructions.

@stefsmeets would you be able to help me? Does it  have to be live as it's my repo or you can actually do it?

**Comment by stefsmeets** [comment]
What is the problem with signing the commits? Did you follow the instructions [here](https://github.com/onnx/onnx/blob/main/CONTRIBUTING.md#dco)?

**Comment by elboyran** [comment]
I tried, but I couldn't apply them as cloning the repo gives me errors, so I cannot continue with the instructions.
