### ISSUE TITLE
Can we make the method selection not case sensitive?

### ISSUE THREAD

**Issue by loostrum** [dianna-ai/dianna#375]
The method name is given as string but needs to be converted to the right case to be able to import the related class.
The generated class name is method name + data modality (Image or Text), where the method name has the same case as whatever the user put in. This leads to some strange errors when the casing is wrong, as DIANNA then wrongly assumes the data modality is to blame. E.g.:
 ```
>>> dianna.explain_image(0, 0, "lime")
Traceback (most recent call last):
  File "/Users/loostrum/projects/DIANNA/dianna/dianna/__init__.py", line 95, in _get_explainer
    method_class = getattr(method_submodule, f"{method}{modality}")
AttributeError: module 'dianna.methods.lime' has no attribute 'limeImage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/loostrum/projects/DIANNA/dianna/dianna/__init__.py", line 58, in explain_image
    explainer = _get_explainer(method, kwargs, modality="Image")
  File "/Users/loostrum/projects/DIANNA/dianna/dianna/__init__.py", line 97, in _get_explainer
    raise XAIMethodException(f"Data modality {modality} is not available for method {method}") from err
dianna.XAIMethodException: Data modality Image is not available for method lime
```

Suggestion: Make the method part of all class names uppercase (`KernelSHAPImage` -> (`KERNELSHAPImage`). Then we can just call `method.upper()` on the user's input.

**Comment by elboyran** [comment]
Yes, go ahead, please.
