### ISSUE TITLE
Add instructions on how to run the tests to README

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#381]
Issue was created as part of #367.

I think we don't have instructions on how to run tests. Especially useful since we are supporting tox which not everyone knows about.
Also, for running without tox, we could add instructions what the current working directory should be in order for the tests to find the test data.

**Comment by loostrum** [comment]
There is this file which includes how to run tests, but it's probably outdated if we never looked at it.. https://github.com/dianna-ai/dianna/blob/main/docs/developer_info.rst
