### ISSUE TITLE
Add a notebook including both training and explaining a model

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#382]
Issue was created as part of #367.

The reviewers ask for a single tutorial showing an "end-to-end" workflow that makes it obvious for novice users how and in what order a user should train and explain a model.

I see their point but at the same time, training models isn't really within our scope. We should take care that this doesn't clutter up our repository instead of clearing things up. Maybe adding a one notebook to the tutorial folder could help novice users to start adopting dianna in their workflows.

**Comment by cwmeijer** [comment]
A figure instead of a notebook makes probably more sense. We should find a place in the documentation where that fits best.

**Comment by elboyran** [comment]
Do we still go for this issue given the paper is approved modulo fixing DOIs? I've recalled that we have already made such figure and included it in the [Documentation.](https://dianna.readthedocs.io/en/latest/usage.html) We have decided to have it there vs in the README, do we reconsider that decision?

**Comment by elboyran** [comment]
It is enough what we have done.
