### ISSUE TITLE
ONNX model for the Weather prediction dataset

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#383]
Train a model for the Weather prediction dataset and convert it to ONNX. 

Follows from #364 
[This issue is best to be picked up by people who have used it in teaching. @geek-yang, @loostrum . @cpranav93 ? ]

**Comment by loostrum** [comment]
I have used this dataset a few times, I'll get started on making a model for it (just reproducing from the lesson material).
In the past we put notebooks for model creation in the dianna-exploration repo, do we still want that?

**Comment by elboyran** [comment]
> I have used this dataset a few times, I'll get started on making a model for it (just reproducing from the lesson material). In the past we put notebooks for model creation in the dianna-exploration repo, do we still want that?

That's a good question. I would say yes, but then in the JOSS paper reviews we got requests to have end-to-end example (including model generation and training, though that's out of scope for DIANNA's functionality IMHO). These are more useful for submitting the models to ONNX zoo for example (I'm working now on #370)

@loostrum, let's put a stand-up label and vote for it's placement today.

**Comment by loostrum** [comment]
PR opened at dianna-exploration: https://github.com/dianna-ai/dianna-exploration/pull/152
The onnx model has also been added to surfdrive.

**Comment by elboyran** [comment]
> PR opened at dianna-exploration: [dianna-ai/dianna-exploration#152](https://github.com/dianna-ai/dianna-exploration/pull/152) The onnx model has also been added to surfdrive.

Nice! I'm looking in to the PR. Could you, please, add the link on surfdrive (to find it quickly when we need it)?

**Comment by loostrum** [comment]
Good point! Hopefully this link works: https://surfdrive.surf.nl/files/index.php/apps/files?dir=/Shared/datasets/weather_prediction
