### ISSUE TITLE
Publish the ONNX Weather prediciton model on zenodo

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#384]
Publish on Zenodo.

Related to #383

**Comment by loostrum** [comment]
Published on Zenodo: https://zenodo.org/record/7543883
The reviewer of this issue could check the record, the metadata can still be changed.

**Comment by elboyran** [comment]
Nice! 
I have 2 small remarks for the description text:

1. Would add ONNX there as well (not only as a key word).
2. (minor) Would say what the De Bilt is ;-) Weather station?

**Comment by loostrum** [comment]
Thanks! I've added those two things to the publication.
