### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#391]
- **Inference**

- [x] Input
- [x] Pre-processing
- [x] Output
- [x] Post-processing

**Comment by cwmeijer** [comment]
This issue should win some medal for highest information to word count ratio ;-P @elboyran, could you elaborate both in the description and the title? What should be the result?

**Comment by elboyran** [comment]
This one and other are produced from my former check-boxes (which you didn't like ;-) ) for the ONNX model zoo issue. So, now they are separate issues linked to the mother one.  I'll work on those, otherwise will be too much overhead for all small ones to describe it all. They are all about sections of the required README.

**Comment by elboyran** [comment]
@loostrum no post-processing is required?

**Comment by elboyran** [comment]
I think @loostrum (invitation to join my repo is pending) is the best person to review this [PR](https://github.com/elboyran/models/pull/3).
I'm not sure I described the model's inference correctly from the [code](https://github.com/dianna-ai/dianna/blob/main/dianna/utils/onnx_runner.py) + [tutorial notebook](https://github.com/dianna-ai/dianna/blob/main/tutorials/lime_images.ipynb).
