### ISSUE TITLE
Test Data Creation

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#393]
- **Test Data Creation**

**Comment by elboyran** [comment]
To update the respective section from the [README (in my repo and proper branch)](https://github.com/elboyran/models/tree/leafsnap30-model/vision/classification/leafsnap30) for our model submission.

**Comment by loostrum** [comment]
Draft PR opened in the models repo: https://github.com/elboyran/models/pull/8

Test data is there, I'm stuck on the step to update the json file as explained in the PR.

**Comment by loostrum** [comment]
I've updated the json file manually, ready for review now. See the PR linked in the previous comment for details.
