### ISSUE TITLE
Update How to Cite section README

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#398]
The How to Cite us section is outdated:

https://github.com/dianna-ai/dianna#how-to-cite-us

**Comment by cpranav93** [comment]
The latest version of Dianna on [Zenodo ](https://zenodo.org/record/7116103) (version 0.5) does not reflect any contributor changes. I am not sure if that is normal or not.

**Comment by loostrum** [comment]
I think that will only update when we do a new release on Github, which should be soon (tm) now that we have the ok for the JOSS authorship
