### ISSUE TITLE
Put coffee model file on surf drive

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#404]
Error: Issue not found.

Just kidding. Model and dataset were still missing from the surfdrive after closing #385.

**Comment by cwmeijer** [comment]
I uploaded both the dataset and the model to:
https://surfdrive.surf.nl/files/index.php/apps/files/?dir=/Projects/Dianna/datasets/coffee&fileid=12142867619
![image](https://user-images.githubusercontent.com/6087314/203366253-1655767b-c326-468a-a4d7-a7b09915295c.png)

**Comment by elboyran** [comment]
Verified ;-)
