### ISSUE TITLE
Dashboard: create collapse menu for parameters

### ISSUE THREAD

**Issue by laurasootes** [dianna-ai/dianna#414]
Maybe a nice to have:

create a dropdown menu in the dashboard for the model parameters:
https://dash-bootstrap-components.opensource.faculty.ai/docs/components/collapse/

(had a quick look at it, but noticed a potential issue with required stylesheet to have it actually collapse
`dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP]))`

**Comment by stefsmeets** [comment]
`dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP]))`

This indeed updates the current styling and messes up the layout to some degree.
