### ISSUE TITLE
Clarify more the research ideas for text and images

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#443]
The proposal sates the following generic research question: 

> Can generic properties of the XAI relevance scores be identified by systematic study?

and

> Not much research on the difficult “explaining the explainer” problem is done  focus on intuitive 
> insights from binary classification on simple datasets.
in Scope:

> Applied research on XAI methods 1-3 (RISE, LIME 
> and KernelSHAP) properties on binary classification 
> of simple image, text and time-series datasets

Make it more concrete, create hypothesis and design initial experiments.

**Comment by elboyran** [comment]
@loostrum would you like to "review" my ideas?

**Comment by loostrum** [comment]
I think these are some nice, concrete tasks that we could work on. For the quantitative work indeed it may be easiest to do this with notebooks. When running the dashboard by hand, we should make sure to store our results from that somehow. Perhaps just make screenshots of interesting results?

**Comment by elboyran** [comment]
>When running the dashboard by hand, we should make sure to store our results from that somehow. Perhaps just make screenshots of interesting results?

Good point, I'll add this to the actual issues description.
