### ISSUE TITLE
Create concrete research tasks as issues: text

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#445]
Start from issue #443.

**Comment by elboyran** [comment]
List of created issues:
#465

**Comment by elboyran** [comment]
@cpranav93 would you, please, have a quick look? It's not the best candidate issue for review, but a second pair of eyes is always good.

**Comment by cpranav93** [comment]
Another interesting research task could be to look in to the best methods for comparing two explained instances. Are relevance maps a good suit? How do we score the relevance maps, etc?

I am not sure if this was already done before, in which case, please ignore the comment.

**Comment by cpranav93** [comment]
I have left a couple of comments as relevant on certain issues. Otherwise it looks like a great break down of the tasks to be done.

**Comment by elboyran** [comment]
> Another interesting research task could be to look in to the best methods for comparing two explained instances. Are relevance maps a good suit? How do we score the relevance maps, etc?
> 
> I am not sure if this was already done before, in which case, please ignore the comment.

I hope some of the literature review by @WillemSpek will give answer to some of these. To the relevance maps as a good suit as well, but for now I think it's nice to limit the scope only on them as they are the main output of dianna. @cpranav93 not sure, what you mean by how do we score them, when I tried to define the quantitative experiments I'm thinking of the actual values of the relevancies which are encoded by the colors in the relevance maps visualization.

Thanks for the comments per issue, I'll have a look at each!

**Comment by elboyran** [comment]
The comments by @cpranav93 for some of the issues are nice suggestions for structuring the work and for additional questions subject to available given the time.
