### ISSUE TITLE
Create concrete research tasks as issues: images

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#446]
Start with ideas from issue #443

**Comment by elboyran** [comment]
Created issues:

#466 (also relevant for text)
#468 (also relevant for text)
#469

**Comment by elboyran** [comment]
@geek-yang would you, please, have a quick look? It's not the best candidate issue for review, but a second pair of eyes is always good.

**Comment by geek-yang** [comment]
> @geek-yang would you, please, have a quick look? It's not the best candidate issue for review, but a second pair of eyes is always good.

I quickly went through all the issues listed here. They all look good to me. There is only one thing I would like to add. 

When addressing these research questions, it is good to document them in a way that could have added value to `dianna`. We can use notebooks to show the codes and results, and wrap-up our findings in markdown files. We can save them in the dianna-exploration repo, and later clean-up the repo and generate a sphinx doc to showcase what we've achieved. For instance, like [Machine Learning 101](https://machinelearning101.readthedocs.io/en/latest/index.html) and [Machine Learning Glossary](https://ml-cheatsheet.readthedocs.io/en/latest/index.html). 

This emphasizes the scientific value of using `dianna`. And it also makes life easier for @WillemSpek to wrap things up as a report 😉.

**Comment by elboyran** [comment]
Great suggestion, thanks @geek-yang!
