### ISSUE TITLE
fix linter issues

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#447]
~Only work on this after #429 and #442 are merged.~

**Comment by cwmeijer** [comment]
```shell
Run prospector
Messages
========

dianna/methods/lime.py
  Line: 2
    pylint: import-error / Unable to import 'lime.lime_image'
  Line: 3
    pylint: import-error / Unable to import 'lime.lime_text'
  Line: 10
    pylint: too-many-arguments / Too many arguments (12/5) (col 4)
  Line: 113
    pylint: too-many-arguments / Too many arguments (8/5) (col 4)

dianna/methods/rise.py
  Line: 47
    pylint: too-many-arguments / Too many arguments (6/5) (col 4)
  Line: 89
    pylint: too-many-arguments / Too many arguments (6/5) (col 4)
  Line: 129
    pylint: too-many-arguments / Too many arguments (6/5) (col 4)
  Line: 150
    pylint: too-many-locals / Too many local variables (16/15) (col 4)

dianna/utils/__init__.py
  Line: 1
    pydocstyle: D104 / Missing docstring in public package

dianna/visualization/__init__.py
  Line: 1
    pydocstyle: D104 / Missing docstring in public package

tests/test_common_usage.py
  Line: 12
    pylint: missing-function-docstring / Missing function or method docstring



Check Information
=================
         Started: 2023-01-17 15:23:40.000975
        Finished: 2023-01-17 15:24:23.868724
      Time Taken: 43.87 seconds
       Formatter: grouped
        Profiles: .prospector.yml, doc_warnings, strictness_medium, strictness_high, strictness_veryhigh, no_member_warnings
      Strictness: from profile
  Libraries Used: 
       Tools Run: dodgy, mccabe, profile-validator, pycodestyle, pydocstyle, pyflakes, pylint, pyroma
  Messages Found: 11
 External Config: pylint: /home/runner/work/dianna/dianna/pyproject.toml

Error: Process completed with exit code 1.
```

**Comment by loostrum** [comment]
Confirming that these message are due to the later version of prospector/pylint. I ran prospector 1.7.7 locally and the results were clean. Updated with `pip install -U prospector[with_pyroma]`, which also updated pylint etc. I now have prospector 1.8.4 and the output is the same as in this issue.

**Comment by cwmeijer** [comment]
Same here ➕1️⃣

**Comment by cwmeijer** [comment]
All linter issues were solved in #450 except for two import issues:
```
Messages
========

dianna\methods\lime.py
  Line: 2
    pylint: import-error / Unable to import 'lime.lime_image'
  Line: 3
    pylint: import-error / Unable to import 'lime.lime_text'
```
This completely makes sense when you take a look at the package:
![image](https://user-images.githubusercontent.com/6087314/213216137-79d6ca65-2dc2-480a-bb3b-e904020ee7af.png)
Note that in the code above we are trying to import dependency ```lime``` from our file called ```lime.py```. I'm actually puzzled that it seems to work in many cases, like for instance while running our tests. Prospector however cannot find the import apparently. It doesn't seem some linter message that I could suppress with a comment but an actual error.

I've been reading about possible solutions. [Here](https://stackoverflow.com/questions/50910341/python-import-name-clash) is one that seems relevant and convenient, but I'm not familiar with the concept of namespaces in python and I'm not sure how it works. Maybe tomorrow :-)

Another option would be to rename our ```lime.py``` in order not to have any clash with our dependency to begin with. This would cause problems in our automatic ```_get_explainer``` loading system (```dianna.__init__.py```; line 85).

**Comment by cwmeijer** [comment]
I disabled the last 2 messages concerning imports. I think it's just pylint complaining, and not an actual error. In the future we might rename our `lime` into something like `lime_image_explainer` which will make these comments redundant.
This issue looks done to me except for reviewing and merging the PR.

**Comment by elboyran** [comment]
@cwmeijer I guess this one can be closed?
