### ISSUE TITLE
try lime-for-time on coffee data set

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#453]
see if we can replicate the results for the coffee dataset.
if so, try it on the weather dataset as well. (other issue)

**Comment by geek-yang** [comment]
Here is a [notebook](https://github.com/emanuel-metzenthin/Lime-For-Time/blob/master/demo/LIME-Pipeline.ipynb) showing how to use LimeforTime to explain the coffee dataset.

**Comment by cwmeijer** [comment]
We ran the notebook and got results that looked similar (or exactly similar?). We didn't have any way to verify whether those results made sense. Therefore we continued with the weather dataset (see #459).
