### ISSUE TITLE
create dashboard mockup

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#454]
with ui improvements
also see #427

**Comment by cwmeijer** [comment]
Mockups after the discussion today.
![dash_mockup_image](https://user-images.githubusercontent.com/6087314/215800804-be57a906-289f-406d-be70-791a63c852a8.jpg)
![dash_mockup_text](https://user-images.githubusercontent.com/6087314/215801094-a2faa07d-2e6d-4cc4-b441-de96066187b9.jpg)

**Comment by elboyran** [comment]
The conceptual Dashboard mock up 

![Dashboard_mockup](https://user-images.githubusercontent.com/3244249/215817708-e9aa2a20-b9fd-480f-a156-c4391cfc6dcc.jpg)

It's also on [DIANNA's Share Point](https://nlesc.sharepoint.com/:i:/s/DIANNA/Ebx6QpLew7pNsOVEewo38Z0BNR9rWnd49QlegeFwmBFYiQ?e=njuWff)

The actual elements are already exsisting and can be seen from Chri's more detailed mock-ups. Try to simplify as soon as possible, e.g. remove/simplify the title "XAI method specific settings"

@cwmeijer , @laurasootes could you, pelase, check it's what we disscussed?

**Comment by elboyran** [comment]
> Looks good! One thing is the XAI method's parameters. Those are method specific and I suggest we therefore move them in the method's (output) section like in my mockups above.

Indeed.
