### ISSUE TITLE
run lime for time on weather dataset

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#459]
Test Lime-for-Time on weather dataset.

**Comment by geek-yang** [comment]
We test the Lime-for-Time approach based on this notebook https://github.com/emanuel-metzenthin/Lime-For-Time/blob/master/demo/LIME-Pipeline.ipynb.

So far the examples included in the tutorial notebook of Lime-for-Time are all univariate timeseries. And it cannot work with inputs with batch size (more than 2 dimensions), see the source code:

https://github.com/emanuel-metzenthin/Lime-For-Time/blob/3af530f778ab2593246cefc1e5fdb28fa872dbdf/lime_timeseries.py#L179-L182

We need to modify this to allow for batch input.

**Comment by geek-yang** [comment]
For more information, here is the link to their paper: [Validation of XAI explanations for multivariate time series classification in the maritime domain](https://github.com/dianna-ai/dianna/files/9859904/1-s2.0-S1877750321001976-main.pdf)

**Comment by geek-yang** [comment]
@cwmeijer and I tested lime for time on weather dataset together. The results seem to make sense. Here the figure shows the importance to the classification of each feature, provided by lime for time.

![image](https://user-images.githubusercontent.com/25911757/217281036-c1a18d4c-42f7-42ea-9ca0-444825ae974a.png)

**Comment by cwmeijer** [comment]
In order to get the simplest case possible with time series data, we retrained a model on the weather data set using only the daily max temperature (univariate case). We then got these results using lime for time:
![image](https://user-images.githubusercontent.com/6087314/220325675-d7e97ba4-a115-4946-98d9-f6b099a0a1f7.png)
As the instance is predicted and annotated as summer, I would expect high saliency values for all days with the highest temperatures. Lime results, however, doesn't show this pattern and all seem very random. This is even using a (very) high number of samples. The results, may look random, they still are quite stable when rerunning the same script.

**Comment by geek-yang** [comment]
Based on the tests and the results we got, it is still very difficult to determine whether Lime-for-Time works well or not, based on the implementation in this notebook https://github.com/emanuel-metzenthin/Lime-For-Time/blob/master/demo/LIME-Pipeline.ipynb. Therefore, we decide to re-investigate this method and try to implement it ourselves.

**Comment by cwmeijer** [comment]
For now, we are closing it and focus on RISE first.
