### ISSUE TITLE
Create notebook template for research of XAI methods on text

### ISSUE THREAD

**Issue by loostrum** [dianna-ai/dianna#464]
Create a notebook in dianna-exploration that runs the movie reviews model.
Set it up such that it can be used to do the research defined in #443

**Comment by elboyran** [comment]
Blocking #474 and #481

**Comment by elboyran** [comment]
According to the [Practicalities](https://github.com/dianna-ai/dianna/issues/443#issuecomment-1383823707) explained in #443, the [notebook](https://github.com/dianna-ai/dianna-exploration/blob/main/relevance_maps_properties/template_notebooks/template_notebook_text.ipynb) resides in [dianna-exploration](https://github.com/dianna-ai/dianna-exploration/tree/main/relevance_maps_properties).
