### ISSUE TITLE
Image experiments: test shape images

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#470]
Create ~10 test images per shape per shape parameter. Start with the [generation script](https://github.com/dianna-ai/dianna-exploration/blob/main/example_data/dataset_preparation/geometric_shapes/generate_geometric_shapes.ipynb) of the [Simple shapes](https://zenodo.org/record/5012825) image dataset to create these test images.

**_Shapes_ are:** _triangle_ and _circle_ (2 in total)

**_Shape_ parameters** are:

- for circles: _size (radius)_ and _gray-scale contrast_ (2 in total)
- for triangles: _size ("radius")_, _rotation angle_ and _gray-scale contrast_ (3 in total)
Gray-scale contrast is defined as the difference between BG and FG colours

For each one of 10 radii sizes: (10 images with different rotation angles and for each rotation angle:) 10 images with varying gray-scale contrast.

**Total**: 100 circles and 1000 triangles.

The output of this issue should be:

- [x] A generation script for the images with functions per shape with all parameters. Stored at the [dataset_preparation folder for Geometric shapes](https://github.com/dianna-ai/dianna-exploration/tree/main/example_data/dataset_preparation/geometric_shapes): generate_geometric_shapes4research.ipynb

- [x] Store the images in .npz  file(s) - the same format as the trained model's data on [Surfdrive](https://surfdrive.surf.nl/files/index.php/apps/files/?dir=/Shared/datasets/geometric_shapes&fileid=9216414968).

Stems from #445 and #443 (see for [Practicalities](https://github.com/dianna-ai/dianna/issues/443#issuecomment-1383823707)).

**Comment by WillemSpek** [comment]
Added this to a new branch ImageExploration in dianna/dianna-exploration repo. Ignore the username.

**Comment by geek-yang** [comment]
I'm still quite curious about XAI's response to the transition of shapes from a triangle to a circle, which was a topic mentioned quite long time ago. But I understand that it is a bit difficult to define this kind of transition quantitatively. If we have extra time, this topic maybe a good candidate as well.

**Comment by elboyran** [comment]
Related to [dianna-exploration PR 158](https://github.com/dianna-ai/dianna-exploration/pull/158)
