### ISSUE TITLE
Remove input text and submit button on dashboard (inconsistent behavior)

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#471]
This is a bit of a borderline of a bug or a feature. The behavior was unexpected to me though.
When I enter 'review one' as text and press `submit` it says `input string is review one`, and then `update explanation` and everything works as expected.

When I then change the input box to 'review two' but don't press submit, the dashboard still says `input string is review one` which is expected (although a bit old-fashioned). When I press `update explanation` it shows me the explanation of 'review two' which is inconsistent.

Rather than fixing this by making it consistent, I would propose to change the design slightly by removing the `submit` button and the `input string is <your input>` text. Technically, they don't seem to do anything anyway. From a user interface perspective, they seem redundant, maybe a little confusing even and they clutter up our crowded dashboard even more. Less is better ;-)

**Comment by stefsmeets** [comment]
I think this is no longer relevant after the dashboard refactor in #548.
