### ISSUE TITLE
Literature review for XAI methods (lime, shap, rise)

### ISSUE THREAD

**Issue by cpranav93** [dianna-ai/dianna#489]
Willem will look at the different methods to understand the explainer.

**Comment by elboyran** [comment]
Would be nice to have the link to the Overleaf in this issue. 
Also maybe leave here as comment the links to the YouTube videos which helped your understanding ;-)

As inspiration for what a useful tool's interface could be and get some feeling on how an XAI method works (LRP in this case) and for some variety while reading lots of papers @WillemSpek feel free to look at some demonstrators by other people:  

- LRP (I really like and am inspired by): https://lrpserver.hhi.fraunhofer.de/
- RISE: https://cs-people.bu.edu/vpetsiuk/rise/demo.html

**Comment by WillemSpek** [comment]
Thanks for the papers @elboyran! Here some of the information 

The link to my review (its still very much in progress at this point):
[https://www.overleaf.com/read/bxwnbrsyjpvq ](url)

A very interesting read showing some core limitations of model-agnostic XAI in Chapter 2: 
[https://link.springer.com/book/10.1007/978-3-031-04083-2 ](url)

YouTube videos that explain LIME and SHAP intuitively: 
[https://youtu.be/d6j6bofhj2M](url)
[https://youtu.be/9haIOplEIGM](url)

**Comment by elboyran** [comment]
Thanks, @WillemSpek! I think we should add the video links to our tutorials or even README!
