### ISSUE TITLE
License not showing in pip show

### ISSUE THREAD

**Issue by WillemSpek** [dianna-ai/dianna#500]
running pip show doesnt show the apache license, this is data presumably generated from the dianna/__init__.py file. I could add the license there

**Comment by stefsmeets** [comment]
I would guess it gets this metadata using [`pkg_resources`](https://setuptools.pypa.io/en/latest/pkg_resources.html) or [`importlib.resources`](https://docs.python.org/3/library/importlib.resources.html). I'm a bit surprised it does not pick up the classifier from `setup.cfg`. 

I tried a few of the other packages I'm working on and they also do not show the licence, so I'd be curious where it actually gets this from 😅👍
