### ISSUE TITLE
missing dependancy on torchtext

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#503]
Trying to run (dianna dev installation) the [rise_text tutorial](https://github.com/dianna-ai/dianna/blob/main/tutorials/rise_text.ipynb)  I got an error when trying to import [torchtext](url).

After installing it with 
`conda install -c pytorch torchtext`
it worked.

(Discovered when working on issue #464.)

**Comment by stefsmeets** [comment]
What error did you run into?
`pytorch` is already part of the dependencies.

**Comment by elboyran** [comment]
Could not find torchtext. After running the first Imports cell.
