### ISSUE TITLE
Dashboard uploads must be located in app_data

### ISSUE THREAD

**Issue by laurasootes** [dianna-ai/dianna#505]
Currently, the data that is uploaded into the dashboard (image, model, label file) must be located in the dashboard/app_data folder. This is not ideal for users.

See "FOLDER_ON_SERVER" in callbacks

**Comment by laurasootes** [comment]
@stefsmeets might be interested in fixing this?

**Comment by stefsmeets** [comment]
What needs fixing? I just tried uploading data outside the app data directory and it seems to work fine.

**Comment by stefsmeets** [comment]
Turns out that the callback does not pass the content of the upload, only the filename.
