### ISSUE TITLE
add channel masking

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#514]
Extend masking code to incorporate masking separate channels. At the moment we can only mask complete time steps.

**Comment by geek-yang** [comment]
Work done. It can be closed.

**Comment by cwmeijer** [comment]
Some resulting masks as an example of the current situation:

Masks (time step, channel and combined; like used in our RISE implementation)
(0=masked, 1=unmasked)
0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 0 1 0 
0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 0 1 0 
0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 0 1 0 
0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 0 1 0 
0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 0 1 0 
0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 0 1 0 
^ channels/ time -->

(0=masked, 1=unmasked)
1 1 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 1 
1 1 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 1 
1 1 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 1 
1 1 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 1 
1 1 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 1 
1 1 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 1 
^ channels/ time -->

(0=masked, 1=unmasked)
1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1 0 1 
1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1 0 1 
1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1 0 1 
1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1 0 1 
1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1 0 1 
1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1 0 1 
^ channels/ time -->

(0=masked, 1=unmasked)
1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 1 
1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 1 
1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 1 
1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 1 
1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 1 
1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 1 
^ channels/ time -->

(0=masked, 1=unmasked)
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
^ channels/ time -->

(0=masked, 1=unmasked)
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
^ channels/ time -->

(0=masked, 1=unmasked)
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
^ channels/ time -->

(0=masked, 1=unmasked)
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
^ channels/ time -->

(0=masked, 1=unmasked)
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 1 0 1 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 1 0 1 0 
1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 1 0 1 0 
^ channels/ time -->

(0=masked, 1=unmasked)
1 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 1 
1 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 1 
^ channels/ time -->

(0=masked, 1=unmasked)
0 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 
0 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
^ channels/ time -->

(0=masked, 1=unmasked)
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0 0 1 
1 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0 0 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0 0 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
^ channels/ time -->

--------------------------------------------------------------------------------------
Masks (just time steps)
(0=masked, 1=unmasked)
0 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1 1 0 1 1 
0 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1 1 0 1 1 
0 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1 1 0 1 1 
0 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1 1 0 1 1 
0 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1 1 0 1 1 
0 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1 1 0 1 1 
^ channels/ time -->

(0=masked, 1=unmasked)
0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 
0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 
0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 
0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 
0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 
0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 
^ channels/ time -->

(0=masked, 1=unmasked)
0 0 0 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 0 
0 0 0 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 0 
0 0 0 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 0 
0 0 0 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 0 
0 0 0 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 0 
0 0 0 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 0 
^ channels/ time -->

--------------------------------------------------------------------------------------
Masks (just channels)
(0=masked, 1=unmasked)
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
^ channels/ time -->

(0=masked, 1=unmasked)
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
^ channels/ time -->

(0=masked, 1=unmasked)
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
^ channels/ time -->
