### ISSUE TITLE
Badges & additional readme paragraphs

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#52]
I would prefer a reorganization of badges on the readme. Thinking about this also made me realize a few things that are missing from the readme.

- [x] The code quality badges should be at the top, just below the title and possibly below a first short descriptive paragraph / tagline. These are: CII checklist, howfairis, Static analysis and coverage. We could also add the CI build badges to this line, but I think these would be better on a next line below the quality badges. 
- [x] They should just be buttons, definitely no table, preferably also no descriptive labels.
- [x] There should just be a readme paragraph at the bottom for license/reusing; the license badge can go at the top of that paragraph.
- [x] The community registry badges should be moved to the top of the installation paragraph. Maybe the code repository one can be included there as well; otherwise imho it could be removed.
- [x] We need a How to cite paragraph; we can move the Zenodo DOI badge there as well.
- [x] Docs badge should go at the top of the documentation paragraph.

**Comment by cwmeijer** [comment]
Some issues that I ran into:
- Our build action is called 'python package' and this is reflected in the badge 'python package passed'. It looks weird and is not very clear. Should we rename the action 'build' instead? Than the badge would say: build passed
- I added a documentation section so the badge could be on top of it. Should we even have such a section? Everything we would write there would be waste of screen space wouldn't it? We could move the badge to the top of the readme and remove the documentation section completely.
- I added a citation section. I'm not sure what to put there. What would we like our users to do?
- We have a coverage badge, which looks fine. @egpbos suggested to include some other static analysis badges. These are the ones available: 
![image](https://user-images.githubusercontent.com/6087314/149761650-419a18e0-ed83-4e39-9b19-ad640fa206e1.png)
None of them is by itself significant enough to place it on top of our Readme I think. We could make a small section with all or a subset of these measures. I think I rather leave them all out as not to distract our users.

Some opinions on any of the issues would be welcome.

**Comment by elboyran** [comment]
After a chat with Faruk I got how we can get a green Howfairis button. Do we wan to to have it? ;-)

**Comment by egpbos** [comment]
@elboyran I don't know what howfairis is. I think we can put it on the more badges page for the time being. What is the final criterion to get it green?

@cwmeijer:

1. Agreed on the build Action rename.
2. Agreed on just putting a docs badge on top instead of a section.
3. Citation section: should mention something like "If you use this package for your scientific work, please consider citing it as: {APA style citation}. See also [Zenodo](link-to-zenodo) to export citation info to bibtex or other formats."
4. I sometimes put a code quality measure badge on top, if I have nothing more important to show. Those typically give some score in the A-F system. I'm fine with leaving it as is for now.

**Comment by elboyran** [comment]
> @elboyran I don't know what howfairis is. I think we can put it on the more badges page for the time being. What is the final criterion to get it green?
> 
We should know and use our own tools ;-)

I think Faruk indicated how to fix it in his recommendation issue #116 . Basically to indicate the CII (?) checklist has been fulfilled. BTW @cwmeijer , you can put an issue to [howfairis](https://github.com/fair-software/howfairis) to change the colour ranking ;-)

**Comment by elboyran** [comment]
Howfairis and one of the recommendations by GT made me think- is it useful to have a supported Python verisons badge?
See the [inspiration](https://github.com/fair-software/howfairis/blob/main/README.rst) for reference.

**Comment by egpbos** [comment]
Todos in this issue:

- [x] build Action rename (done in #90).
- [x] putting a docs badge on top instead of a section (included in #113).
- [ ] Citation section: should mention something like "If you use this package for your scientific work, please consider citing it as: {APA style citation}. See also Zenodo to export citation info to bibtex or other formats."
- [ ] Add green howfairis badge to readme
- [ ] Add supported python versions badge to readme

**Comment by egpbos** [comment]
Final todo has gotten its own issue, have to wait for #113 to be merged for that one. Closing! :)
