### ISSUE TITLE
Implement tensor axis labeling for DIANNA completely

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#53]
A few times, and again today from Matthieu, the issue came up that getting the tensor axes in the correct order is a huge annoyance and/or confuses users. The preprocessing function provides a way to fix it, but it is still difficult to wrap one's head around.

To make not only DIANNA but really all of tensor-based deep learning more convenient, it would help if we had a tensor type with annotated axes. Something that acts like

```python
class AnnotatedAxesTensor:
    def __init__(self, data, axis_labels):
        ...

batch_size = 20
channels = 38
fidgets = 10
worbles = 204
sigwatts = 2

data = np.zeros((batch_size, channels, fidgets, worbles, sigwatts))

t = AnnotatedAxesTensor(data, ["batch", "channel", "fidget", "worble", "sigwatt"])

print(t.batch[0])
```

which would output the first batch. Models that use these tensors will be able to "transpose" / rotate axes in the underlying tensor automatically, which will make the user input side a lot easier. It can also give a warning when it does indeed need to reshape the underlying tensor, because this may impact performance, so the user may want to reshape beforehand, but now it will be easy, because the implementation warning can just say exactly how they should do the reshaping:

```python
print("please reshape for optimal performance: t.rotate_axes["batch", "sigwatt", "worble" ...]")
```

I realize that this may be out of scope for the DIANNA project currently, but maybe this is something to look into in the future, if you think it would be useful.

**Comment by cwmeijer** [comment]
I think this could be its own package/repo as it has little to do with DIANNA other than that we want to use it :-)

We could include some checks that give warnings if the number of channels for an image is not 1 or 3 etc.

**Comment by egpbos** [comment]
Agreed, could be a spin-off. Just wanted to put the idea out there.

**Comment by egpbos** [comment]
Maybe good to look into `xarray`.

**Comment by loostrum** [comment]
I played around with `xarray` and implemented something in the `xarray` branch as a test for #55.

**Comment by egpbos** [comment]
I came across this as well: https://pytorch.org/docs/stable/named_tensor.html 

From what I read, this is not universally supported even within PyTorch itself (let alone outside, of course). Still, may be worth looking into how much exactly and how it compares to `xarray`.

**Comment by loostrum** [comment]
The Pytorch named tensor looks interesting. I see a few pros/cons w.r.t xarray:

- pro: no need to specify a name for all columns
- reordering columns seems easier (moving channels is even an explicit example)
- con: we would need to depend on a very big library for just a small feature
- con(?): It is a prototype feature, less mature than xarray. The API may change

**Comment by egpbos** [comment]
Would be nice if conversion between xarray and NamedTensor were possible and easy.
