### ISSUE TITLE
Make plan to change dashboard technology to increase testability and maintainability

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#542]

**Comment by stefsmeets** [comment]
I made a little prototype in the branch: https://github.com/dianna-ai/dianna/tree/dashboard

![afbeelding](https://user-images.githubusercontent.com/873520/230103059-0e8c3d79-aeb7-4cf9-9012-6a42fcc5d675.png)

Have a look and let me know what you think. If you wish to try it, you can use:

```
git checkout dashboard --
pip install streamlit
cd dashboard2
streamlit run dashboard.py --server.headless True
```

It uses [streamlit](https://docs.streamlit.io/) as the framework for the layout. I tried to mimick the current layout and functionality as well as possible. 

One of my goals was to use `dianna.visualization.plot_image` for the visualizations. For now I only looked at the image page. RISE and LIME are working.  KernelSHAP is also pretty much working, but I need to figure out how to pass the onnx model to `explain_image`.

**Comment by stefsmeets** [comment]
Text page:

![Screenshot 2023-04-06 104946](https://user-images.githubusercontent.com/873520/230328270-6ce40428-651e-49a8-93a9-402d1bc4c998.png)
