### ISSUE TITLE
Report experimental design for experiments

### ISSUE THREAD

**Issue by WillemSpek** [dianna-ai/dianna#550]
Write a paragraph containing the following

- [x] Description of qualitative view of evaluation 
- [x] Selection of evaluation qualities to be assessed. 
- [x] Selection of evaluation methods based on these qualities.
- [x] Description of synthetic data used for modelling 
- [x] Description of models used for modelling
- [x] Assemble in project proposal

Use the directions identified in issue #547

**Comment by elboyran** [comment]
Left comments on the Overleaf project. Missing some info about the used models.
