### ISSUE TITLE
resnet visualisation in dashboard

### ISSUE THREAD

**Issue by laurasootes** [dianna-ai/dianna#552]
The current dashboard output for the reset model looks like the attached screenshot. This output is generated using the Dianna visualisation. This is different from the visualisation in the readme. I am not sure why the visualisation is different. The main difference are as follows:

- the color coding is r/b instead of rgb.
- the original figure is not visible anymore (transparency issue? or not plotted?)
- I wonder if the shown image is flipped (not sure)

![image](https://user-images.githubusercontent.com/95367983/231406193-54c877e2-1fb8-4237-b89f-8194ce7e0111.png)

**Comment by stefsmeets** [comment]
The color map is specified in the dashboard: https://github.com/dianna-ai/dianna/blob/06a9e5cfee3d53152d133d888f60501cfcbb9abe/dashboard/pages/1_images.py#L118

**Comment by laurasootes** [comment]
resnet no longer in dashboard
