### ISSUE TITLE
Add timeseries functionality to dashboard

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#568]
See lime (and rise) notebooks in tutorials

https://github.com/dianna-ai/dianna/blob/main/tutorials/rise_timeseries_weather.ipynb
https://github.com/dianna-ai/dianna/blob/main/tutorials/lime_timeseries_weather.ipynb

**Comment by stefsmeets** [comment]
This is what I have for now:

![Screenshot 2023-04-25 163756](https://user-images.githubusercontent.com/873520/234311987-cc863317-fc14-439d-abda-83f15018c539.png)

Some issues that I ran into:

- [ ] LIME timeseries interface is not complete yet. The output returns zeroes and the `explain_timeseries` function is inconsistent with RISE. This results i 
- [ ] Should explain_timeseries return (normalized) segments?
- [ ] What will the data format for timeseries look like? For now I just load a `.npy` file with a single column of y values. I can imagine this should be some pandas data frame or numpy array with xy data instead.
