### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by WillemSpek** [dianna-ai/dianna#582]
Looks like a lot of the dependencies in the dianna-exploration repo are now deprecated and need to be resolved. I am not keen on changing the versions too aggresively as this might adversely affect the rest of the codebase.

**Comment by stefsmeets** [comment]
Yeah, tricky problem. Although it's not like all the notebooks would break all of a sudden. Would it make sense to have a `requirements.txt` per notebook?

I also see that the requiments specifies all the transitive dependencies, which are already pulled in py the dianna import. It might be easier to maintain the dependencies if the repo just specifies the direct dependencies only (`dianna` and maybe some others that are not pulled in by dianna).

You could split this in a `requirements.in` with the direct dependencies and a `requirementst.txt` file with all dependencies.

**Comment by elboyran** [comment]
Is this issue done then?
