### ISSUE TITLE
Keep track of data types

### ISSUE THREAD

**Issue by loostrum** [dianna-ai/dianna#59]
In some cases, the user may provide data with one data type, but the XAI methods produces model input with another data type. We should keep track of this, and convert the data back to the correct type before feeding it to the model.

**Comment by cwmeijer** [comment]
We don't fully understand what you mean. Could you give more details and a plan how to solve it?

**Comment by loostrum** [comment]
In some cases the data/model it may e.g. expect float32, which somewhere in the XAI method gets converted to float64 and we'd have to convert back to float32 before feeding data to the model. 
Could be solved by storing the input dtype, then calling data.astype(dtype) before feeding to the model. I'll work on implementing that now
