### ISSUE TITLE
recompile list with non gradient XAI methods

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#64]

**Comment by elboyran** [comment]
The initial list of methods we have compiled and evaluated: https://nlesc.sharepoint.com/:w:/s/DIANNA/ET7gE4Wd-jlCq_rm0qjvJ9MBF-38sLKVaEWtMskUPJPiKw?e=OX7LFZ

**Comment by elboyran** [comment]
---This comment is work in progress ----
From our initial lists I did not see any other method which can replace our DeepLIFT shap which is not gradient-based (needs back-prop and/or the internals of the model). Then I expanded a bit my search and came by 2 methods outside our lists with pluses and minuses:

| Method | Paper(s) | Implementation | Advantages | Disadvantages |
|  :--------- |  :--------- |  :--------- |  :--------- | :--------- |
| Method | Paper(s) | Implementation | Advantages | Disadvantages |
| Method | Paper(s) | Implementation | Advantages | Disadvantages |
