### ISSUE TITLE
unify the function outputs in the API

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#640]
Create an overview in this issue with outputs changed etc.
Consider using an output parser that can be reused and tested

**Comment by elboyran** [comment]
Depends on issue #639

**Comment by SarahAlidoost** [comment]
Based on #663 and #691, here is a list of proposed changes:
- [ ] make the Type of output the same for each data type ([view 1 in the table](https://github.com/dianna-ai/dianna/blob/add_overview/docs/IO_overview.md#dianna-functions-view-1))
- [ ] make the value range of output the same for each method ([view 2 in the table](https://github.com/dianna-ai/dianna/blob/add_overview/docs/IO_overview.md#dianna-functions-view-2))
- [ ] fix API documentation that matches the implementation
- [ ] In case it is not possible to unify, the reasons should be documented.

**Comment by SarahAlidoost** [comment]
@cwmeijer  and @elboyran  [kernelshap_image.py](https://github.com/dianna-ai/dianna/blob/61004edaa7d7596917f9a85de591415be3d0d330/dianna/methods/kernelshap_image.py#L131) module returns a tuple as `shap_values, self.image_segments`. Is it necessary to return `self.image_segments`? if so, can we convert the private function `_segment_image` to a public function so users can create the `image_segments` if needed. This change is necessary to unify the outputs.

**Comment by elboyran** [comment]
@cwmeijer do you know the answer to the first question?

**Comment by SarahAlidoost** [comment]
Currently, the outputs of both lime and rise methods on text data are a list of (word, index of word in raw text, importance for target class) per class. However, it seems that the `index of word in raw text` is not used anywhere. For example, in [visualization text](https://github.com/dianna-ai/dianna/blob/f4736d4746e4651100139a9f6ec9ca5487c94627/dianna/visualization/text.py#L34-L40), a dictionary of `importance_map` is created using `word` and `importance`.
