### ISSUE TITLE
List options to validate kwargs

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#655]
Validate all kwargs from explainers in top-level function

Also see #130

**Comment by cpranav93** [comment]
One possible solution:
https://stackoverflow.com/questions/196960/can-you-list-the-keyword-arguments-a-function-receives

**Comment by cpranav93** [comment]
A more direct method: https://stackoverflow.com/questions/31200594/python-check-required-kwargs-in-a-function

This would require us to have a very clear idea of what exactly is needed and to update it any time things change.
