### ISSUE TITLE
Inquire about the possibility of adding CAM series methods to dianna

### ISSUE THREAD

**Issue by KerwinKai** [dianna-ai/dianna#657]
Hi all contributors, dianna is one of the very few XAI library supporting the onnx format. For me, this is the only tool I can find that supports this feature. However, many interpretability methods have been developed in the XAI field. I raise this issue to ask whether visualization tools represented by grad_cam can be added to dianna like [pytorch-cnn-visualizations](https://github.com/utkuozbulak/pytorch-cnn-visualizations).

**Comment by cwmeijer** [comment]
Hi @KerwinKai,

Thanks for your interest in our library and for opening an issue.

Grad_cam and any other gradient based methods are not supported in DIANNA. This is related to our choice for ONNX as a model format. ONNX format doesn't store the gradients and is therefore not ideally suited to be used with gradient based methods. To avoid dependency on gradients or other extra information about the insides of models and also in order not to have to deal with ONNX version specifics, we focus on XAI methods that handle purely black box models.

I hope this anwers your question and am therefore closing this issue. Let us know if you have more questions, issues or suggestions.

Cheers,

**Comment by KerwinKai** [comment]
Thx, the answer solved my question～
