### ISSUE TITLE
Create an overview (table?) of all input types and output types (including dimension names)

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#663]
For both our XAI methods and the visualizations.
For using with dianna.explain but also RISE.explainer().explain
Also note if we are using Typing at these points.

Discuss the outcome with the team.

**Comment by elboyran** [comment]
The overview table to be stored on [SharePoint](https://nlesc.sharepoint.com/:w:/s/DIANNA/ETzPMmSeuhlLiihn-54umzwBtcRprlh469PM3BKxIRcYbQ?e=c9Apak).

**Comment by elboyran** [comment]
[Drawio schematic of the DIANNA architecture](https://app.diagrams.net/#Wb!UPZtKeipi0WrFvKBlrEPP4gCzfYL1_ZNqqeyKlYhp43xuB7DeGf3QZ8Mqz5yc_MZ%2F01YA33DUNHOZDA5F2365C2HPUKXVPAOSOR)

Needs logging in with Microsoft credentials.

**Comment by elboyran** [comment]
Another starting point for the overview is our [API documentaiton](https://dianna.readthedocs.io/en/latest/autoapi/index.html).
