### ISSUE TITLE
LIME explain_image design choice; forward kwargs to methods

### ISSUE THREAD

**Issue by mlaneuville** [dianna-ai/dianna#68]
LIME `explain_image` directly returns 
`mask = explanation.get_image_and_mask(label, positive_only=False, hide_rest=True, num_features=num_features)[1]`
without giving the user the opportunity to change `positive_only`, `hide_rest`, or play with parameters such as `min_weight`.

What was the reasoning behind this choice of default parameters? 
Would it be useful to give the user the opportunity to pass those values if needed?

The user will likely stumble upon the base LIME implementation documentation even when trying to use the DIANNA wrapper and that documentation demonstrates interesting flexibility in how to visualize the mask:
https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20images.html

**Comment by egpbos** [comment]
I think (correct me if I'm wrong) we just didn't get to implementing method dependent keyword arguments yet, good suggestion!

**Comment by egpbos** [comment]
Working on this in https://github.com/dianna-ai/dianna/tree/68_method_kwargs

**Comment by egpbos** [comment]
Draft PR in #73
