### ISSUE TITLE
Prepare presentation for section meeting

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#685]

**Comment by cwmeijer** [comment]
@cpranav93 Could you please add a link to the presentation in this issue?

**Comment by cpranav93** [comment]
[Uploading dianna_env_section_18012024.pptx…]()

**Comment by cpranav93** [comment]
[Dianna PPT](https://nlesc.sharepoint.com/:p:/s/DIANNA/Eche8kbXOctMjV9rhqHKQlkBdmLeNI5QxLvLQalVayGj_A?e=zg0186)
