### ISSUE TITLE
Publish our trained ONNX models in Zenodo

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#695]
- Time-series

- [x] Coffee model

- Tabular

- [x] Penguin model (classification)
- [x] Sunshine hours prediction model (regression)

- [x] Update the README

- [x] Add these into RSD from their Zenodo DOIs. (@elboyran has the RSD page maintenance rights.)

**Comment by elboyran** [comment]
see also #683 as there is some duplication.

**Comment by elboyran** [comment]
Coffee model [draft Zenodo entry](https://zenodo.org/uploads/10579458)

**Comment by elboyran** [comment]
@cpranav93 , @cwmeijer could you, please. check if the drafts are OK?

**Comment by elboyran** [comment]
Updated the [RSD DAINNA project entry](https://research-software-directory.org/projects/dianna)

**Comment by elboyran** [comment]
PR #704

**Comment by cpranav93** [comment]
Had a look at the zenodo links and entries. It looks perfectly fine!
