### ISSUE TITLE
Dianna poster for NAC 24

### ISSUE THREAD

**Issue by SarahAlidoost** [dianna-ai/dianna#715]
see #668 
The poster is on on teams -> `General/abstracts/EGU24_dianna.pptx`

see https://nwonac.nl/

**Comment by elboyran** [comment]
Hi @SarahAlidoost , I've looked at it and did a few edits directly in the text (sorry, couldn't find how to do review suggestions in PowerPoint!) I also have left a comment on the contributors to DIANNA. Not sure you want to update the tutorial's table to include the latest RFB from Leon (being still a work in progress). Overall- looks great!
