### ISSUE TITLE
Make simple flyers/cards to distribute at conferences, e.g. ICT Open etc.

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#736]
- [x] Generate QR code for https://dianna-ai.github.io/dianna/
- [x] Design front and back sides of the flyer/card
- [x] Order

Order 30-50 10.5 x 10.5 cm. simple double-sided flyers containing DIANNA's logo, "slogan", QR code, and link to the GitHub page from issue #702.
See the presentation slides' right bottom corner as an example starting point (issue #734)

**Comment by elboyran** [comment]
Possible flyer sites:

- [Drukwerknodig.nl](https://www.drukwerknodig.nl/promotie/flyers/)
- [Drukland.nl](https://www.drukland.nl/drukken/flyers)

[QR code generator](https://app.qr-code-generator.com/) **12 days free usage left!**

**Comment by loostrum** [comment]
That link seems to work only when logged in, perhaps you can share screenshots through teams?

**Comment by elboyran** [comment]
> That link seems to work only when logged in, perhaps you can share screenshots through teams?

@loostrum , @SarahAlidoost I posted screenshots in Teams.

**Comment by elboyran** [comment]
Veronica convinced me to go for bussiness cards. I've forwarded her email. Let me know if you like the design.
