### ISSUE TITLE
add notebook for eulaw case

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#756]
add a notebook to the tutorials

also, make sure the linking from the notebook to the models and dataset on zenodo work nicely.

**Comment by elboyran** [comment]
@cwmeijer is the tutorial ready?

Please, don't forget to also update the [Datasets](https://github.com/dianna-ai/dianna?tab=readme-ov-file#datasets), [Models](https://github.com/dianna-ai/dianna?tab=readme-ov-file#onnx-models) and [Tutorials table](https://github.com/dianna-ai/dianna?tab=readme-ov-file#scientific-use-cases) in the main README and the [task](https://github.com/dianna-ai/dianna/tree/main/tutorials#scientific-use-cases) and [tutorial](https://github.com/dianna-ai/dianna/tree/main/tutorials#scientific-use-cases-1) tables in the Tutorial's README with links related to the new tutorial when ready! Also to add a column to the relevant [Hyperparamer's table](https://github.com/dianna-ai/dianna/tree/main/tutorials#important-hyperparameters).

For the sake of budget saving, I could also do this (with a possible small help to locate the data and model links), after a successful PR merge (passing all checks).
