### ISSUE TITLE
create notebook using DIANNA on the ecoextreml model and data

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#759]

**Comment by elboyran** [comment]
@SarahAlidoost, nice work! I'm only not able to see the result figures in the Review Notebook mode.

Please, don't forget to also update the [Datasets](https://github.com/dianna-ai/dianna?tab=readme-ov-file#datasets), [Models](https://github.com/dianna-ai/dianna?tab=readme-ov-file#onnx-models) and [Tutorials table](https://github.com/dianna-ai/dianna?tab=readme-ov-file#scientific-use-cases) in the main README and the [task](https://github.com/dianna-ai/dianna/tree/main/tutorials#scientific-use-cases) and [tutorial](https://github.com/dianna-ai/dianna/tree/main/tutorials#scientific-use-cases-1) tables in the Tutorial's README with links related to the new tutorial!

For the sake of budget saving, I could also do this (with a possible small help to locate the data and model links), after a successful PR merge (passing all checks).

**Comment by SarahAlidoost** [comment]
> @SarahAlidoost, nice work! I'm only not able to see the result figures in the Review Notebook mode.
> 
Thanks, I also noticed that the figures are not rendered correctly. It is fixed now. 

> Please, don't forget to also update the [Datasets](https://github.com/dianna-ai/dianna?tab=readme-ov-file#datasets), [Models](https://github.com/dianna-ai/dianna?tab=readme-ov-file#onnx-models) and [Tutorials table](https://github.com/dianna-ai/dianna?tab=readme-ov-file#scientific-use-cases) in the main README and the [task](https://github.com/dianna-ai/dianna/tree/main/tutorials#scientific-use-cases) and [tutorial](https://github.com/dianna-ai/dianna/tree/main/tutorials#scientific-use-cases-1) tables in the Tutorial's README with links related to the new tutorial!
> 
> For the sake of budget saving, I could also do this (with a possible small help to locate the data and model links), after a successful PR merge (passing all checks).

In PR #811, I added the items to the section below, can you please help to complete them:

[Datasets in main README](https://github.com/dianna-ai/dianna/tree/add_emulator_nb?tab=readme-ov-file#tabular): can you help with an image for **Examples** cell?
[Models in main README](https://github.com/dianna-ai/dianna/tree/add_emulator_nb?tab=readme-ov-file#tabular-1): done 
[Tutorials table in main README](https://github.com/dianna-ai/dianna/tree/add_emulator_nb?tab=readme-ov-file#scientific-use-cases): done
[task in Tutorial's README](https://github.com/dianna-ai/dianna/tree/add_emulator_nb/tutorials#scientific-use-cases): can you help with an image for **Logo** cell?
[tutorial in Tutorial's README](https://github.com/dianna-ai/dianna/tree/add_emulator_nb/tutorials#scientific-use-cases-1): can you help with logo and collab link?

**Comment by elboyran** [comment]
@SarahAlidoost , sure I can help. 

I have made some commits to address the help you have asked for (in the process also fixing some old broken links in the READMEs.

IMHO there is still a little bit of final polishing needed, namely (sorry for forgetting some of them in the issue/comments before):

- [x] add the used hyperparameters in the [KernalSHAP hyperparameter table](https://github.com/dianna-ai/dianna/blob/add_emulator_nb/tutorials/README.md#kernelshap) 
- [x] Adding a word explaining what the physical model is for in the [task description table](https://github.com/dianna-ai/dianna/blob/add_emulator_nb/tutorials/README.md#scientific-use-cases)
- [x] Adding 1 sentence to the [notebook](https://github.com/dianna-ai/dianna/blob/add_emulator_nb/tutorials/explainers/KernelSHAP/kernelshap_tabular_land_atmosphere.ipynb) introduction paragraph summarizing very briefly what the scientific problem to be helped by the model is. You have given nice references, but a single sentence could save interested scientists the time to dig and read the whole paper. Sorry, I didn't feel competent to make such a sentence myself from e.g. the [eEcoExtremeML project description](https://research-software-directory.org/projects/ecoextreml).

**Comment by SarahAlidoost** [comment]
> @SarahAlidoost , sure I can help.
> 
> I have made some commits to address the help you have asked for (in the process also fixing some old broken links in the READMEs.
> 
> IMHO there is still a little bit of final polishing needed, namely (sorry for forgetting some of them in the issue/comments before):
> 
> * [x]  add the used hyperparameters in the [KernalSHAP hyperparameter table](https://github.com/dianna-ai/dianna/blob/add_emulator_nb/tutorials/README.md#kernelshap)
> * [x]  Adding a word explaining what the physical model is for in the [task description table](https://github.com/dianna-ai/dianna/blob/add_emulator_nb/tutorials/README.md#scientific-use-cases)
> * [x]  Adding 1 sentence to the [notebook](https://github.com/dianna-ai/dianna/blob/add_emulator_nb/tutorials/explainers/KernelSHAP/kernelshap_tabular_land_atmosphere.ipynb) introduction paragraph summarizing very briefly what the scientific problem to be helped by the model is. You have given nice references, but a single sentence could save interested scientists the time to dig and read the whole paper. Sorry, I didn't feel competent to make such a sentence myself from e.g. the [eEcoExtremeML project description](https://research-software-directory.org/projects/ecoextreml).

@elboyran thanks. I addressed your comments in the last three commits https://github.com/dianna-ai/dianna/pull/811. Please let me know if we can merge the PR.
