### ISSUE TITLE
lure Jesus into our project

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#763]

**Comment by elboyran** [comment]
For now consider only the separate use-cases?

**Comment by cwmeijer** [comment]
I just had a chat with him, too. He estimates about 70-80 hours for a 30-60 second promotional video.

**Comment by cwmeijer** [comment]
I added a standup label to discuss what to do next.

**Comment by elboyran** [comment]
He advised us to use Powerpoint. Shared the [RSD video](https://research.software/) and design ideas for inspiration. 

<img width="1165" alt="image (1)" src="https://github.com/dianna-ai/dianna/assets/3244249/9bd0cd82-f0ba-4cce-af40-9ff3cda90290">

Slide 1 [Closeup of RSD logo in white circle]:"Imagine a hub for all your research software needs."
Slide 2 [Zoom out to reveal complete logo]:"Welcome to the Research Software Directory, where impact and usability come together to amplify research and discovery."
Slide 3 [Letters transform into FIND, SHARE, RECOGNIZE]:"Your place to FIND, SHARE, and RECOGNIZE valuable research applications."
Slide 4 [Show FIND page with visuals of software browsing]:"Dive into our vast compilation of software packages where relevancy and quality are prominent. Quick and efficient discovery at your fingertips."
Slide 5 [Transition to SHARE page with visuals of software submission]:"Bring your software to light. Share your work and collaborate with others around the globe."
Slide 6 [Transition to RECOGNIZE page with visuals of citation info]:"Recognition for innovation.  "
Slide 7 [Back to RSD logo]:"Join us in our mission to make research software accessible, efficient, and give credit where it's due."
Slide 8 [Website Link & Contact Email]:"On Research Software Directory, we believe in the power of open and reusable software, join us today."
