### ISSUE TITLE
make plan for creating an FRB video

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#785]
Also use this issue to brainstorm? add ideas here

**Comment by elboyran** [comment]
Asked Communications today. They might be able to help, but some work (more than I thpught) is involved. 

Want detailed email what we want and timeline and maybe could ask Tom & DT for some ComCom budget (if I convince them is useful for the evaluation....)

**Comment by elboyran** [comment]
My initial idea: 3-4 minutes (thought 10, but Veronica and Francies said no way ;-) ) video with 2 related parts:

1. "Interview" or a chat-style with Leon and Joeri (to sparkle the interest to watch further)
2. Leon teaches how it's done using the notebook (for the now interested people to do it themselves).

If good idea- I can also say few sentences as an Intro.

For that we need Joeri's availability (Communications said probably min half day for recordings), not sure if all can be prepared and done "before the summer" (~ 15 July?).

**Comment by SarahAlidoost** [comment]
It would be nice if the 3-4 minute video tells a compelling story connecting with the public and highlighting societal impact. I suggest using graphical images and visualizations instead of showing the notebook. The chat-interview style is great and can be incorporated as commentary throughout the video.

**Comment by elboyran** [comment]
Communications are **not** doing video editing. 
Asked if they know software, was pointed to the Apple's [IMovie](https://itunes.apple.com/us/app/imovie/id408981434).

**Comment by elboyran** [comment]
Brainstorm session on FRB videos (https://github.com/dianna-ai/dianna/issues/785)
2024-06-20
Present: Leon, Sarah, Laura, Elena, Chris

We decided we want 2 separate videos for the FRB use case.

1. ‘promotional’ video 
Elements to include: 
-	interview with Juri about scientific case
-	interview with Leon about DIANNA
-	show images of frbs, telescopes, etc
-	dashboards?
audience would be other astronomers
goal messages:
-	Dianna is useful
-	Dianna is easy

Possible scene 1: societal impact
Possible scene 2: Promise what we will be able to do with tools that we are developing now

Footage: flythrough on Westerbork telescope
Message
“See our other tutorials”

2 Teaching video
Teaching astronomers how to use dianna. Notebook tutorial
Similar to Giulia’s video. Can be longer if needed.

Actions:
-	Find out for license (elena)
-	Write script for scientific part of promotional video (powerpoint?) (leon)
-	Ask Lefman (youtuber) about editing tools (chris)

**Comment by elboyran** [comment]
Make 2 separate issues and close this one?
