### ISSUE TITLE
create new release

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#786]
wait for rise-tabular to be merged #730

**Comment by cwmeijer** [comment]
![Image](https://github.com/dianna-ai/dianna/assets/6087314/4ba5013e-c22b-4d64-a6bd-14dba5039e00)

https://pypi.org/project/dianna/

**Comment by elboyran** [comment]
Hm, the build is failing on dashboard tests! @cwmeijer , @laurasootes could you plese, look into this?
