### ISSUE TITLE
make all our zenodo entries shared

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#787]
in zenodo press the share button etc. shared access

**Comment by loostrum** [comment]
I checked my [Zenodo dashboard](https://zenodo.org/me/uploads) and I have two DIANNA related uploads:
[The ONNX weather prediction model](https://zenodo.org/records/7543883)
[DIANNA itself](https://zenodo.org/records/10955891)

I've shared both with @cwmeijer and @elboyran, with manage access.

**Comment by elboyran** [comment]
Added as owners @cwmeijer and @loostrum to
-   [ONNX model trained on the Coffee dataset](https://zenodo.org/records/10579458)
- 

> I checked my [Zenodo dashboard](https://zenodo.org/me/uploads) and I have two DIANNA related uploads: [The ONNX weather prediction model](https://zenodo.org/records/7543883) [DIANNA itself](https://zenodo.org/records/10955891)
> 
> I've shared both with [@cwmeijer](https://github.com/cwmeijer) and [@elboyran](https://github.com/elboyran), with manage access.

Strange that you don't see models you are the only author of, e.g the Stanford sentiment treebank. Will check and share all the entries I see.

**Comment by loostrum** [comment]
That is weird indeed. I found the [LeafSnap30](https://zenodo.org/records/5907196) model as well in my account, but I can't seem to share it

**Comment by elboyran** [comment]
Also, I added as managers @cwmeijer and @loostrum to
- [ONNX model trained on the Coffee dataset](https://zenodo.org/records/10579458)
- [ONNX and PyTorch models trained on Stanford sentiment treebank dataset](https://zenodo.org/records/5910598)
- [ONNX model trained on the binary MNIST dataset](https://zenodo.org/records/5907177)
- [ONNX model trained on the Penguins dataset](https://zenodo.org/records/10580743)
- [ONNX model trained on the Simple geometric dataset](https://zenodo.org/records/5907059)
