### ISSUE TITLE
Add tabular example in dashboard

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#789]
As a start use the [LIME](https://github.com/dianna-ai/dianna/blob/main/tutorials/explainers/LIME/lime_tabular_penguin.ipynb) and [KernelSHAP](https://github.com/dianna-ai/dianna/blob/main/tutorials/explainers/KernelSHAP/kernelshap_tabular_penguin.ipynb) tutorials on the penguin data (classification task).

Brainstorm oh can we add also the regression examples [LIME](https://github.com/dianna-ai/dianna/blob/main/tutorials/explainers/LIME/lime_tabular_weather.ipynb) and [KernelSHAP](https://github.com/dianna-ai/dianna/blob/main/tutorials/explainers/KernelSHAP/kernelshap_tabular_weather.ipynb) on the weather datatset?

**Comment by cwmeijer** [comment]
Because the weather dataset was already demoed in the time series tab, we chose to go with the penguins dataset.
