### ISSUE TITLE
Dashboard redesign?

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#791]
Brainstorm if and how to redesign the dashboard to show 

`Toy examples`
and
`Scientific use-cases`
separately

Ask also Stef and/or Jesus to join for an hour?

**Comment by elboyran** [comment]
Blocking #790 and (maybe #789 ?)

**Comment by elboyran** [comment]
Could it be as easy as having indented "menu" on the left (now having all the modalities) 

(image of the situation now)


![Image](https://github.com/dianna-ai/dianna/assets/3244249/948cf36c-888d-4db0-a6a2-b55c9548e5ef)



to having (new in italic):

- Home

- _All modalities simple examples_
--- Images
--- Text
--- Time series (TS)
--- _Tabular (Tab)_

- _Scientific use-cases examples_
--- _Astronomy: Fast Radio Burst (FRB) detection (TS)_
--- _Social science (?): EU law analysis (Text)_
--- _Earth science (?): ?? (Tab)_

Pinging @SarahAlidoost for the best name of her use case and @cwmeijer for checking the name and domain for his.

**Comment by laurasootes** [comment]
[Dashboard mochup](https://nlesc.sharepoint.com/:p:/s/DIANNA/EZPsRj4LDYpBm_YmFRP1QCcBR1kZfpwHE4def0dcNg4HnA?e=pq3T57) as discussed Jun 27 2024

**Comment by elboyran** [comment]
@laurasootes , I left some comments in the dashboard mockup file. 
(Sorry some of t hem I attached the the exact visual element, but some are per slide as I forgot to click on the element first. Let me know if these are clear, or I should attach them)

**Comment by laurasootes** [comment]
Thanks! I will look at them on Wednesday

Laura

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by elboyran** [comment]
Any other opinions on the slides? @loostrum, @cwmeijer, @SarahAlidoost ?
When ideas are finalized, we should also create new issue(s) for the actual redesign and close this one.

**Comment by elboyran** [comment]
Concrete new redesign issues so far: #816, #817, #818 , #819.
