### ISSUE TITLE
Link to DIANNA tutorials in docs leads to 404 error

### ISSUE THREAD

**Issue by ClaireDons** [dianna-ai/dianna#795]
The link to the DIANNA tutorials in ["How to use DIANNA"](https://dianna.readthedocs.io/en/latest/usage.html) leads to a [404 error](https://dianna.readthedocs.io/en/latest/tutorials). It may need to link to [this page](https://github.com/dianna-ai/dianna/tree/main/tutorials#tutorials) instead. 

This may be due to the docs needing to be updated as some typos appear in [https://dianna.readthedocs.io/en/latest/tutorials/0-overview.html](https://dianna.readthedocs.io/en/latest/tutorials/0-overview.html) which are not present [here](https://github.com/dianna-ai/dianna/blob/main/tutorials/overview.ipynb)

**Comment by elboyran** [comment]
After merging the #797 the result should be: https://dianna.readthedocs.io/en/795-link2tutorials-documentaion/usage.html
and following the tutorials link should go directly to the overview tutorial.
Not sure what it was pointing to before.
