### ISSUE TITLE
Compare complete saliency map to expected one in RISE tests on images

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#80]
All other method tests compare the complete explanation result to a stored one except the RISE test on images, which only compares output shapes.

Standup label: discuss whether to do in this sprint or later.

**Comment by cwmeijer** [comment]
standup conclusion: we should add this to the tests. Not in sprint 12 though because there's not enough time.

**Comment by elboyran** [comment]
Expected LIME heatmaps should be added to the [test data](https://github.com/dianna-ai/dianna/tree/main/tests/test_data) and then compared to the RISE result on images in [test_rise.py](https://github.com/dianna-ai/dianna/blob/main/tests/test_rise.py).
See test_lime_function and test_rise_function in [test_lime.py](https://github.com/dianna-ai/dianna/blob/main/tests/test_lime.py)

**Comment by loostrum** [comment]
You mean that RISE heatmaps should be added, right? We can't compare LIME
heatmaps to RISE results.
I'll have a look at adding these

**Comment by elboyran** [comment]
@loostrum yes, add RISE heatmaps to be reference for comparison in the tests.
