### ISSUE TITLE
List possible video edit software

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#810]
What software is Abel using?
What software is Lefman (friend Chris) using?
What licenses does communication have?
What is Jesus using?

List pros and cons if possible.

**Comment by elboyran** [comment]
Communications are **not** doing video editing. 
Asked if they know some software, was pointed to the Apple's [IMovie](https://itunes.apple.com/us/app/imovie/id408981434).

**Comment by elboyran** [comment]
Jesus uses [Capcut](https://www.capcut.com/).

**Comment by cwmeijer** [comment]
My friend uses hitfilm by fxhome. He says it has an intuitive interface.

**Comment by cwmeijer** [comment]
Abel recommended KDEnlive. KDEnlive is quite good and moderately easy to use he says. It's best to use video sources of the same resolution (e.g., 1920x1080) to avoid scaling issues. Simply load the files into the project, drag them into the timeline, then cut and move as needed. For adding background music, overlays, and transitions, there are extra steps—we can ask him for help in that case, he said.

**Comment by cwmeijer** [comment]
Maybe we should start by trying KDEnlive

**Comment by elboyran** [comment]
I have also just came across and downloaded the free video-editor [Filmora](https://filmora.wondershare.com/video-editor/).
