### ISSUE TITLE
Dashboard: add text

### ISSUE THREAD

**Issue by laurasootes** [dianna-ai/dianna#816]
Add some more text to make the use of the dashboard and the examples a bit clearer. Specifically:

- [x] Landing page: rename “pages”, and clarify what images/text/timeseries means in this context
- [x] Landing page: what is the dashboard
- [x] Page titles: make page titles more informative than simple “Image explanation"
- Examples: explain what the example is: what is the data, what is the task, what do the colours mean Image classification page:
- [x] Image classification
- [x] Tabular classification
- [x] Tabular regression
- [x]  Text classification
- [x] Time series classification weather
- [x] Time series classification FRB

Suggestion from Sarah to remove the pages section fully

**Comment by elboyran** [comment]
Adding this comment in the first seemingly relevant still open issue I found:

- [ ] fix typos and reformulate a bit.
![image](https://github.com/user-attachments/assets/982c9ede-68e8-4cd7-9949-d237103755c7)

- [ ] edit to avoid repetitions
![image](https://github.com/user-attachments/assets/4434b47e-679a-4519-b51f-c368e19384f5)

**Comment by elboyran** [comment]
For the colors of the attribution maps, borrow/get inspired by this nice [explanation](https://arxiv.org/pdf/2206.03208v1#subsubsection.A.3.1).

**Comment by elboyran** [comment]
Landing page implemented: 
![image](https://github.com/user-attachments/assets/7b1b4210-1eb3-4042-81c1-09fc77e10d05)

**Comment by elboyran** [comment]
Image page and example:

![image](https://github.com/user-attachments/assets/918f0fa7-c289-484b-8df9-e3315e770193)
-----------------------------------------------
![image](https://github.com/user-attachments/assets/094f226b-0587-4051-9964-da67195d33d6)

**Comment by elboyran** [comment]
Tabular page and examples:

![image](https://github.com/user-attachments/assets/c97027cc-3dd2-4a44-997c-c72864149910)
------------------------------------------------
![image](https://github.com/user-attachments/assets/c5f847ab-e9e0-4822-969f-6ec7601699b4)
--------------------------------------------------
![image](https://github.com/user-attachments/assets/63ad42e6-5f85-4532-a595-7e92a55f57de)

**Comment by elboyran** [comment]
Text page and examples:

![image](https://github.com/user-attachments/assets/b0dc16a5-e0a6-4b5e-a561-0426822370a4)
--------------------------------------

![image](https://github.com/user-attachments/assets/2664c5f6-1dd8-4dcd-aa2b-259852aa64b9)

**Comment by elboyran** [comment]
Time series page and examples:

![image](https://github.com/user-attachments/assets/320fbe81-37a1-48b0-a844-fce4f9b27f67)
------------------------------------------
![image](https://github.com/user-attachments/assets/93d1a9c9-25c3-4bb3-99b8-6d17a8d7ce8e)

------------------------------------------
![image](https://github.com/user-attachments/assets/70019723-e608-49f4-a7f3-2103bb7c9d20)
