### ISSUE TITLE
torchtext end-of-life and broken

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#829]
As noted in #827 and other recent PRs with breaking CI workflows, the torchtext package seems to be breaking down. It is no longer being developed (see https://github.com/pytorch/text/issues/2250).

Some options:

1. Find a workaround ourselves.
2. Look for a fork that **is** still maintained and switch to that.
3. Replace torchtext as a dependency.

Option 3 seems the most attractive to me, naively, but I haven't looked deeply into how unique the functionality is that we use. We only use torchtext in two ways:

- `from torchtext.data import get_tokenizer` in `utils/tokenizer.py`
- `from torchtext.vocab import Vectors` in `test/utils.py`, in a couple of notebooks and in the dashboard.

Can these easily be replaced? If not, a fourth option presents itself:

4. Cannibalize torchtext for these parts only.

**Comment by loostrum** [comment]
Yikes, I guess we should have followed up on the deprecation warning earlier ;) 
I'll see if we can replace torchtext. In the linked pytorch issue they also suggest taking from the torchtext source what you need, so option 4. may not be the worst idea, we can just put them in a dianna text utils file.

**Comment by cwmeijer** [comment]
[Spacy](https://github.com/explosion/spaCy), a dependency of DIANNA already, may provide both functionalities. Looking at their code, it seems so. I came across a `vocab.Vectors` and a `get_tokenizer` in their code. That would be a nice solution I think (that's an option 3 for ya 😉).

**Comment by SarahAlidoost** [comment]
As a temporary fix to get CI green again, torch version is pinned in #841. Once this issue is resolved, the temporary fix can be removed.

**Comment by egpbos** [comment]
We may need to take another look at a more future-proof solution for this, because we may be running against the limits of the pinned versions we're using now. E.g. [this notebook run](https://github.com/dianna-ai/dianna/actions/runs/25170854839/job/73790264787?pr=879) may be failing due to outdated circular dependencies between `pytorch_lightning` and other torch stuff (not sure yet, but even if this is not the issue in this particular case, it's probably still going to be causing issues if we don't upgrade torch beyond 2.3.1 now).

There are a couple of references to this issue both in commit texts and in code (e.g. in the install python action yml file), so for clarity I'm reopening this one instead of creating a new issue.

**Comment by egpbos** [comment]
I didn't realize the torchtext dependency itself was already gone since #853, nice! That means we can drop the workaround version pins again. Working on this in #883.

The problem in the notebook run above is fixed and turned out to be unrelated. However, to futureproof the library, we should still unpin things. For instance, the spacy pin (also being unpinned in #883) kept us from upgrading to numpy 2, which is long overdue. Because of numpy 2's backwards incompatible changes, some other libraries also could not upgrade, like shap which was also pinned down to the pre-numpy 2 version (not completely sure that was the reason, since the commit and the PR #727 don't explain this). And it would also lead to incompatibilities with other libraries that users may want to have installed in the same environment, so for that reason alone we should unpin as much as we can.
