### ISSUE TITLE
Add demos to the main repo

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#83]
Let's include @loostrum's demos in the main repo! https://github.com/loostrum/dianna_demo

**Comment by cwmeijer** [comment]
we dsicussed it in the standup: sounds good

**Comment by egpbos** [comment]
@loostrum is this still needed or is all your work basically in the existing tutorials?

**Comment by loostrum** [comment]
I checked and it's all in the existing tutorials, closing this issue.
