### ISSUE TITLE
Build action fails due to `torchtext` OSError --> undefined symbol

### ISSUE THREAD

**Issue by SarahAlidoost** [dianna-ai/dianna#837]
The issue is reported [here](https://github.com/pytorch/text/issues/1342). The current Dianna GitHub actions installed `pytorch 2.4` and `torchtext 0.18.0` which are not compatible according to [this table](https://github.com/pytorch/text#installation).

**Comment by cwmeijer** [comment]
This will also be solved once #829 is fixed but that will take a little time. Only fix this if it's super easy as it will be very temporary problem anyway.
