### ISSUE TITLE
Fix the DOI in tutorials/explainers/KernelSHAP/kernelshap_tabular_land_atmosphere.ipynb

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#854]
https://github.com/dianna-ai/dianna/actions/runs/10918707919/job/30304762201?pr=847

**Comment by elboyran** [comment]
For some reason the [DOI]([https://zenodo.org/doi/10.5281/zenodo.12623256](https://zenodo.org/doi/10.5281/zenodo.12623256) doesn't exist any more!?

**Comment by loostrum** [comment]
I tried the failing line manually and it works fine now, I think it was an intermittent issue.
The DOI links in the CI do contain an error, the link includes the ")." at the end in the URL. That's just the error message, the actual downloader works. 

I've clicked rerun for the failing tests, if they pass now I'll close the issue

**Comment by loostrum** [comment]
CI is all green again in recent runs, so closing this issue.
