### ISSUE TITLE
Fix mac-os notebook and build fails

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#861]
See: 

- [notebooks](https://github.com/dianna-ai/dianna/actions/runs/11161693398/job/31024779164)
- [build 3.9](https://github.com/dianna-ai/dianna/actions/runs/11161693382/job/31024780466)
- [build 3.11](https://github.com/dianna-ai/dianna/actions/runs/11161693382/job/31024780807)

**Comment by loostrum** [comment]
This is very strange, the macos runner decides to install numpy 1.19, which is 1. pretty old and 2. _below_ our minimum requirement of 1.20. Apparently there are no wheels for this numpy version and macos version combination, and building from source fails.

I don't see exactly why this is happening. I did notice that linux and windows get a dianna install from the cache, so nothing new is installed. For macos this doesn't happen an a clean install is started, but that now fails.

An ugly workaround might be to install a newer numpy explicitly before installing dianna itself

**Comment by loostrum** [comment]
I've tried a few things (see #862), but it doesn't work yet.
