### ISSUE TITLE
Tutorial notebook for LIME for images.

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#97]
1 example per notebook.
Use the dataset in the exploration repo. 
We want to cover binary MNIST. OR triangles and circles OR LeafSnap datasets and cover all in all notebooks.

**Comment by loostrum** [comment]
I wll use leafsnap for this notebook.

**Comment by loostrum** [comment]
Ran into a few issues that could be worked around, but it would be better IMO to fix them before finishing the tutorial notebooks. See issues #108 and #110, and PR #109.

**Comment by loostrum** [comment]
Blocked by #108 and #110
